Neonnumber
TheAlgorithms/Java pull request #1564
Opened 2020-10-03 02:56 UTC by Aman1kr

NEON NUMBER:

A neon number is a number where the sum of digits of square of the number is equal to the number. For example if the input number is 9, its square is 9*9 = 81 and sum of the digits is 9. i.e. 9 is a neon number.

### **Describe your change:**

* [ ] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

#### References

### **Checklist:**

* [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
* [ ] This pull request is all my own work -- I have not plagiarized.
* [ ] I know that pull requests will not be merged if they fail the automated tests.
* [ ] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ ] All new Java files are placed inside an existing directory.
* [ ] All filenames are in all uppercase characters with no spaces or dashes.
* [ ] All functions and variable names follow Java naming conventions.
* [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-03 09:36 UTC, yansheng836 reviewed
Maybe you should pay attention to these problems:
1. add package name, like `package Maths;`.
2. add doc/comment for class/method.
3. solve the problem in the special method, not in main method, main only for test.


for example:<https://github.com/TheAlgorithms/Java/blob/master/Maths/Area.java>

2020-10-13 15:36 UTC, deadshotsb requested changes

2020-10-13 15:36 UTC, deadshotsb commented on Maths/Neonnumber
> +import java.util.*;
Kindly do the changes + give a.java extension to the file

2020-10-13 15:36 UTC, closed without merging

2020-10-13 15:36 UTC, deadshotsb commented
I am closing the pr at this moment kindly do the changes and reopen it.