Create GenericStackList.JAVA
TheAlgorithms/Java pull request #1907
Opened 2020-10-21 21:39 UTC by P-N-C

### **Describe your change:**

* [X] Add an algorithm?
* [ ] Fix a bug or typo in an existing algorithm?
* [ ] Documentation change?

#### References

### **Checklist:**

* [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Java files are placed inside an existing directory.
* [] All filenames are in all uppercase characters with no spaces or dashes.
* [X] All functions and variable names follow Java naming conventions.
* [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-10-21 21:40 UTC, P-N-C commented
Posted a Generic Stack implemented by using Linked List

2020-11-19 09:21 UTC, aravinth2094 requested changes

2020-11-19 09:21 UTC, aravinth2094 commented on DataStructures/Stacks/GenericStackList.JAVA
> +	public Link create_link(E it, Link nextval) {
Please follow java conventions for a more standard experience.
```suggestion
	public Link createLink(E it, Link nextVal) {
```

2020-11-19 09:21 UTC, aravinth2094 commented on DataStructures/Stacks/GenericStackList.JAVA
> +			if(temp == head) System.out.print(temp.next.element);
Please use getters/setters as it promotes the use of abstraction in java.
```suggestion
			if(temp == head) System.out.print(temp.getNext().getElement());
```

2020-11-19 09:21 UTC, aravinth2094 commented on DataStructures/Stacks/GenericStackList.JAVA
> +	int cnt;
Please consider adopting a more comprehensive nomenclature.
```suggestion
	int count;
```

2020-11-19 09:21 UTC, aravinth2094 commented on DataStructures/Stacks/GenericStackList.JAVA
> +public class Stack <E> {
I highly encourage documentation for the class and its methods.

2020-11-19 10:31 UTC, P-N-C commented
Thank you, I am going to update my code once my college exams ends.

2020-11-19 10:39 UTC, aravinth2094 commented
> Thank you, I am going to update my code once my college exams ends.

Great, All the best!

2020-11-19 15:36 UTC, ayaankhan98 reviewed
also please add the relevant documentation and rename file to change extension from `.JAVA` to `.java` whenever you update this PR.

2021-09-26 05:38 UTC, closed without merging