Create MulAddSubThreads.java
TheAlgorithms/Java pull request #1927
Opened 2020-10-24 04:30 UTC by gokulmanohar

First file commit for MultiThreading directory. Response for Issue (#1926).

### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

Created a new Multithreading directory for including multithreading programs. Included an arithmetic program for finding sum, product and difference of two operands using multithreading on java.

#### References

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2020-11-14 14:31 UTC, prashantdoshi28 requested changes
Make sure all checks are passing for PR.

2020-11-14 14:31 UTC, prashantdoshi28 commented on MultiThreading/MulAddSubThreads.java
> +public class MulAddSubThreads{
Please add proper documentation for your code.

2020-11-15 17:50 UTC, ayaankhan98 commented on MultiThreading/MulAddSubThreads.java
> +class Mul extends Thread {
better to use `Runnable` Interface

2020-11-15 17:50 UTC, ayaankhan98 commented on MultiThreading/MulAddSubThreads.java
> +class Add extends Thread {
same goes here

2020-11-15 17:50 UTC, ayaankhan98 commented on MultiThreading/MulAddSubThreads.java
> +class Sub extends Thread {
here too.

2021-09-26 05:37 UTC, closed without merging