Added BinaryExponentiation.java
TheAlgorithms/Java pull request #2359
Opened 2021-10-01 06:10 UTC by PranayChauhan2516

### **Describe your change:**

- [X] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

### **Checklist:**

- [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [X] This pull request is all my own work -- I have not plagiarized.
- [X] I know that pull requests will not be merged if they fail the automated tests.
- [X] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [X] All new Java files are placed inside an existing directory.
- [X] All filenames are in all uppercase characters with no spaces or dashes.
- [X] All functions and variable names follow Java naming conventions.
- [X] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.

2021-10-04 17:55 UTC, siriak approved these changes

2021-10-04 17:56 UTC, siriak requested changes
Build is failing

2021-10-05 04:43 UTC, PranayChauhan2516 commented
I have done the necessary changes.

2021-10-05 10:58 UTC, siriak approved these changes
Thanks!

2021-10-05 10:59 UTC, merged