Add Happy numbers problem in "others" category
TheAlgorithms/Java pull request #2839
Opened 2021-11-23 12:14 UTC by louvelbr

### **Describe your change:**

- [x] Add an algorithm? 
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

Issue number : #2832

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.

2021-11-24 08:21 UTC, siriak commented
Hi, the build is failing with the following error: ./src/main/java/com/thealgorithms/others/HappyNumbersSeq.java:4: error: class HappyNumSeqTest is public, should be declared in a file named HappyNumSeqTest.java
public class HappyNumSeqTest {
       ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

2021-11-24 08:23 UTC, siriak requested changes

2021-11-24 08:23 UTC, siriak commented on src/main/java/com/thealgorithms/searches/LinearSearchThread.java
> +package search;
Package names are not correct, please see correct ones in other files

2021-11-24 08:23 UTC, siriak commented on src/main/java/com/thealgorithms/others/HappyNumbersSeq.java
> +	}
Having some formatting would be great

2021-11-25 09:14 UTC, yanglbme approved these changes

2021-11-25 09:18 UTC, yanglbme commented
Hi @siriak , please review again.

2021-11-25 18:35 UTC, siriak reviewed
Only a couple of small comments, everything else looks good :)

2021-11-25 18:35 UTC, siriak commented on src/main/java/com/thealgorithms/searches/LinearSearchThread.java
> +                found = true;
Please short-circuit execution here, no need to continue iterations

2021-11-25 18:35 UTC, siriak commented on src/main/java/com/thealgorithms/searches/LinearSearchThread.java
> +        this.x = x;
Please improve naming. array, leftIndex, rightIndex,...

2021-11-26 17:35 UTC, siriak approved these changes

2021-11-26 17:35 UTC, merged