Add algorithms_random_node.java in lists section
TheAlgorithms/Java pull request #2851
Opened 2021-11-29 12:41 UTC by skmodi649

### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References : Issue = select random node in Linked list

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All functions and variable names follow Java naming conventions.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{2850}`.

2021-11-29 12:44 UTC, skmodi649 reviewed
Reviewed!

2021-11-29 13:01 UTC, skmodi649 reviewed
Prettified the code!

2021-11-29 13:03 UTC, yanglbme requested changes

2021-11-29 13:03 UTC, yanglbme commented on src/main/java/com/thealgorithms/datastructures/lists/Algorithms_random_node.java
> +public class Algorithms_random_node {
Class Name should be `Camel-Case`

2021-11-29 13:03 UTC, yanglbme commented on src/main/java/com/thealgorithms/datastructures/lists/Algorithms_random_node.java
> +public class Algorithms_random_node {
```suggestion
public class RandomNode {
```

2021-11-29 13:03 UTC, yanglbme commented on src/main/java/com/thealgorithms/datastructures/lists/Algorithms_random_node.java
> +        list = new ArrayList < > ();
```suggestion
        list = new ArrayList <>();
```

2021-11-29 13:03 UTC, yanglbme commented on src/main/java/com/thealgorithms/datastructures/lists/Algorithms_random_node.java
> +        int random_num = list.getRandom();
```suggestion
        int randomNum = list.getRandom();
```

2021-11-29 17:53 UTC, skmodi649 commented on src/main/java/com/thealgorithms/datastructures/lists/Algorithms_random_node.java
> +public class Algorithms_random_node {
Change made!

2021-11-29 17:53 UTC, skmodi649 commented on src/main/java/com/thealgorithms/datastructures/lists/Algorithms_random_node.java
> +public class Algorithms_random_node {
Change made!

2021-11-29 17:53 UTC, skmodi649 commented on src/main/java/com/thealgorithms/datastructures/lists/Algorithms_random_node.java
> +        list = new ArrayList < > ();
Change made!

2021-11-29 17:53 UTC, skmodi649 commented on src/main/java/com/thealgorithms/datastructures/lists/Algorithms_random_node.java
> +        int random_num = list.getRandom();
Change made!

2021-11-29 17:54 UTC, skmodi649 reviewed
Changes made!

2021-11-29 19:57 UTC, skmodi649 reviewed
Changes made and reviewed!

2021-11-30 01:44 UTC, yanglbme approved these changes

2021-11-30 02:22 UTC, merged

2021-11-30 03:08 UTC, skmodi649 reviewed
Reviewed!