My Commit for the Issue #2864 Pascal's Triangle
TheAlgorithms/Java pull request #2871
Opened 2021-12-10 09:27 UTC by iamhardikat11

### **Describe your change:**

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

### **Checklist:**

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ] All new Java files are placed inside an existing directory.
- [ ] All filenames are in all uppercase characters with no spaces or dashes.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-12-10 09:34 UTC, iamhardikat11 commented
Made my PR. Please Review and Respond.

2021-12-11 16:58 UTC, siriak requested changes
I've left a small comment about automated tests, everything else looks good!

2021-12-11 16:58 UTC, siriak commented on src/main/java/com/thealgorithms/maths/PascalTriangle.java
> +    }
```suggestion
    public static int[][] pascal(int n)
    {
        /**
         * @param arr  An auxiliary array to store generated pascal triangle values
         * @return
         */
        int[][] arr = new int[n][n];


        /**
         * @param line Iterate through every line and print integer(s) in it
         * @param i Represents the column number of the element we are currently on
         */
        for (int line = 0; line < n; line++)
        {
            /**
             *  @Every line has number of integers equal to line number
             */
            for (int i = 0; i <= line; i++)
            {
                // First and last values in every row are 1
                if (line == i || i == 0)
                    arr[line][i] = 1;
                    // The rest elements are sum of values just above and left of above
                else
                    arr[line][i] = arr[line-1][i-1] + arr[line-1][i];
            }
        }
        
        return arr;
    }
```

2021-12-11 16:58 UTC, siriak commented on src/main/java/com/thealgorithms/maths/PascalTriangle.java
> +    }
Please remove the main() method and add some automated tests as was done in https://github.com/TheAlgorithms/Java/pull/2869/files, thanks!

2021-12-12 17:16 UTC, siriak submitted a review, later dismissed
The build is failing because of a typo in the last test at com.thealgorithms.maths.ArrayLeftRotationTest.testForEight(PascalTriangleTest.java:38). Please fix it, everything else is solid, thanks!

2021-12-12 17:44 UTC, iamhardikat11 commented
This task (Build/build(pull_request)) is failing everytime I try, what can be done?

2021-12-12 18:03 UTC, iamhardikat11 commented
I have resolved all Checks please Merge my PR.

2021-12-13 20:04 UTC, siriak approved these changes
LGTM, thanks!

2021-12-13 20:04 UTC, merged