add UniquePath
TheAlgorithms/Java pull request #2873
Opened 2021-12-11 00:35 UTC by zzq1zh

### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.

2021-12-12 17:23 UTC, siriak requested changes

2021-12-12 17:23 UTC, siriak commented on src/main/java/com/thealgorithms/dynamicprogramming/UniquePaths.java
> +
Please remove main() and add some tests as in https://github.com/TheAlgorithms/Java/pull/2871/files

2022-01-19 04:37 UTC, siddhant2002 commented
Can I work under this issue?

2022-01-19 05:54 UTC, zhrgithub commented
Of  curse


| |
张泓锐
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年01月19日 12:39，Siddhant Swarup ***@***.***> 写道：

Can I work under this issue?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2022-02-16 05:23 UTC, siddhant2002 commented
@siriak please check the updated pr as I've added the tests.

2022-02-19 11:59 UTC, closed without merging