MaximumSubArraySum
TheAlgorithms/Java pull request #2877
Opened 2021-12-12 12:50 UTC by Ayse-Sadioglu

### **Describe your change:**

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

### **Checklist:**

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ] All new Java files are placed inside an existing directory.
- [ ] All filenames are in all uppercase characters with no spaces or dashes.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2021-12-12 17:21 UTC, siriak requested changes
Looks good, please add some tests as in https://github.com/TheAlgorithms/Java/pull/2871/files

2021-12-12 17:21 UTC, siriak commented on src/main/java/com/thealgorithms/others/MaximumSubArraySum.java
> +        int leftMax = -1000000000;
Please use  Integer.MIN_VALUE

2021-12-12 17:21 UTC, siriak commented on src/main/java/com/thealgorithms/others/MaximumSubArraySum.java
> +        int rightMax = -1000000000;//should be minimum value
And here

2021-12-12 17:21 UTC, siriak commented on src/main/java/com/thealgorithms/others/MaximumSubArraySum.java
> +
```suggestion

```

2021-12-12 17:21 UTC, siriak commented on src/main/java/com/thealgorithms/others/MaximumSubArraySum.java
> +}
```suggestion
    }
}

```

2022-01-19 04:36 UTC, siddhant2002 commented
Can I work under this issue?

2022-01-19 19:32 UTC, siriak commented
@siddhant2002 yes, feel free to implement this

2022-01-26 20:04 UTC, 22aam reviewed
the code looks good to me

2022-02-10 03:40 UTC, siddhant2002 commented
@siriak please check the pr

2022-02-10 17:03 UTC, siriak commented
@siddhant2002 which one? I've already reviewed this one

2022-02-11 03:27 UTC, siddhant2002 commented
@siriak please check the updated pr

2022-02-12 13:37 UTC, siriak commented
Superseded by #2913

2022-02-12 13:37 UTC, closed without merging