refactor: Refactored calculateMaxOfMin() (#5)
TheAlgorithms/Java pull request #2957
Opened 2022-02-22 16:43 UTC by chubretovic

Refactored the function calcultateMaxOfMin form the class MaximinumMinimumWindow.

2022-03-08 15:42 UTC, siriak commented on pom.xml
> +</project>
```suggestion
</project>

```

2022-03-08 15:44 UTC, siriak requested changes
Looks good, only a couple of comments

2022-03-08 15:44 UTC, siriak commented on src/main/java/com/thealgorithms/datastructures/stacks/MaximumMinimumWindow.java
> +        //assert Arrays.equals(target, res);
Please remove main()

2022-03-08 15:45 UTC, siriak commented
And please update to the latest master

2022-04-25 18:24 UTC, siddhant2002 commented
Can I work under this issue?

2022-04-26 20:38 UTC, siriak commented
@siddhant2002 yes, you can

2022-06-13 00:22 UTC, closed without merging