Wigglesort
TheAlgorithms/Java pull request #3032
Opened 2022-04-21 08:52 UTC by BranAndSceolan

### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-04-23 19:31 UTC, siriak requested changes

2022-04-23 19:31 UTC, siriak commented on src/main/java/com/thealgorithms/sorts/WiggleSort.java
> + * A wriggle sort implementation based on John L.s' answer in
```suggestion
 * A wiggle sort implementation based on John L.s' answer in
```

2022-04-23 19:31 UTC, siriak commented on src/main/java/com/thealgorithms/sorts/WiggleSort.java
> +        }
These are the same, you could have used floor for both branches

2022-04-23 19:31 UTC, siriak commented on src/main/java/com/thealgorithms/sorts/WiggleSort.java
> +        System.out.println(median);
Please remove stdout output

2022-04-23 19:31 UTC, siriak commented on src/main/java/com/thealgorithms/sorts/WiggleSort.java
> +    public static void main(String[] args) {
Please add automated tests with @Test instead of main()

2022-04-24 07:13 UTC, BranAndSceolan commented
Thank you for reviewing, I have made the changes you requested.

2022-04-25 13:46 UTC, siriak approved these changes
LGTM, thanks!

2022-04-25 13:54 UTC, merged