Adding new data structure
TheAlgorithms/Java pull request #3037
Opened 2022-04-27 11:51 UTC by omarmahamid

### **Describe your change:**

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

### **Checklist:**

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ] All new Java files are placed inside an existing directory.
- [ ] All filenames are in all uppercase characters with no spaces or dashes.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-04-27 12:10 UTC, omarmahamid commented
this a data structure that I implement in my university (you can see it in my github https://github.com/omarmahamid/DS)

2022-04-28 10:15 UTC, omarmahamid commented
@siriak @yanglbme

2022-04-30 09:46 UTC, siriak requested changes

2022-04-30 09:46 UTC, siriak commented on src/main/java/com/thealgorithms/datastructures/heaps/FibonacciHeap.java
> +    private static final double GOLDAN_RATIO = (1+Math.sqrt(5))/2;
```suggestion
    private static final double GOLDEN_RATIO = (1+Math.sqrt(5))/2;
```

2022-04-30 09:46 UTC, siriak commented on src/main/java/com/thealgorithms/datastructures/heaps/FibonacciHeap.java
> +    }
Please replace this with tests using `@Test`, see examples in the codebase in the `src/test` directory

2022-04-30 09:46 UTC, siriak commented on src/main/java/com/thealgorithms/datastructures/heaps/FibonacciHeap.java
> +	private static int totalLinks = 0;
Please replace tabs with spaces

2022-05-01 07:30 UTC, siriak commented on src/main/java/com/thealgorithms/datastructures/heaps/FibonacciHeap.java
> +	}
Tabs

2022-05-01 16:19 UTC, omarmahamid commented on src/main/java/com/thealgorithms/datastructures/heaps/FibonacciHeap.java
> +	}
done

2022-05-02 15:54 UTC, siriak approved these changes
LGTM, thanks!

2022-05-02 15:56 UTC, merged