Added Isomorphic Strings
TheAlgorithms/Java pull request #3244
Opened 2022-09-01 04:55 UTC by Mann-tech13

### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #3236`.

2022-09-04 15:03 UTC, siriak requested changes

2022-09-04 15:03 UTC, siriak commented on src/main/java/com/thealgorithms/strings/Isomorphic.java
> +    boolean check = true;
Please rename it to something meaningful

2022-09-04 15:03 UTC, siriak commented on src/main/java/com/thealgorithms/strings/Isomorphic.java
> +    Set<Character> set = new HashSet<Character>();
And these variables too

2022-09-04 15:03 UTC, siriak commented on src/test/java/com/thealgorithms/strings/Isomorphic.java
> +  public static boolean isIsomorphic(String s, String t) {
Please add tests and remove duplication

2022-09-06 05:12 UTC, Mann-tech13 commented on src/test/java/com/thealgorithms/strings/Isomorphic.java
> +  public static boolean isIsomorphic(String s, String t) {
Okay, I'll do it by today

2022-09-06 16:03 UTC, closed without merging