Perimeter Calculator
TheAlgorithms/Java pull request #3247
Opened 2022-09-02 17:17 UTC by poorvadiwan

I went through the Maths section of the repository and found programs for volume and area but not perimeter. So this is a program to calculate perimeter of geometrical objects.

- [x] Add an algorithm?

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] All functions and variable names follow Java naming conventions.

2022-09-06 17:19 UTC, siriak requested changes

2022-09-06 17:19 UTC, siriak commented on src/main/java/com/thealgorithms/maths/Perimeter.java
> +    public static float perimeter_polygon( int n, float side){
Please fix formatting

2022-09-06 17:19 UTC, siriak commented on src/main/java/com/thealgorithms/maths/Perimeter.java
> +    public static float perimeter_rectangle( float len, float brea){
Please use full words instead

2022-09-06 17:19 UTC, siriak commented on src/main/java/com/thealgorithms/maths/Perimeter.java
> +
No need for this newline

2022-09-06 17:19 UTC, siriak reviewed
Please also add some JUnit tests

2022-09-07 17:49 UTC, poorvadiwan commented
I have completed the changes you asked!! 
I apologize for the mess, actually, I am new to GitHub so I was a bit confused.

2022-09-08 07:04 UTC, siriak approved these changes
Looks good, thanks!

2022-09-08 07:05 UTC, merged