Added Isomorphic strings with the changes
TheAlgorithms/Java pull request #3253
Opened 2022-09-06 16:06 UTC by Mann-tech13

### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All functions and variable names follow Java naming conventions.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #3236 `.

2022-09-06 17:14 UTC, siriak requested changes
No need to re-create a PR, just make your changes and they'll be reflected here

2022-09-06 17:14 UTC, siriak commented on src/main/java/com/thealgorithms/strings/Isomorphic.java
> +    boolean check = true;
Please rename it to something meaningful

2022-09-06 17:14 UTC, siriak commented on src/main/java/com/thealgorithms/strings/Isomorphic.java
> +                break;
Use `return false;` instead

2022-09-06 17:14 UTC, siriak commented on src/test/java/com/thealgorithms/strings/IsomorphicTest.java
> +
Please correct formatting

2022-09-07 08:56 UTC, Mann-tech13 commented
All changes updated in current pull request.

2022-09-08 07:09 UTC, siriak requested changes

2022-09-08 07:09 UTC, siriak commented on src/test/java/com/thealgorithms/strings/IsomorphicTest.java
> + */
This comment is useless

2022-09-08 07:09 UTC, siriak commented on src/test/java/com/thealgorithms/strings/IsomorphicTest.java
> +  public static void main(String[] args) {
![image](https://user-images.githubusercontent.com/29201949/189057162-86a32629-b9dd-44a1-89e1-9eefec4f3229.png)
Indentation is inconsistent and it's not the entry point

2022-09-08 07:09 UTC, siriak commented on src/test/java/com/thealgorithms/strings/IsomorphicTest.java
> +
Why have so many empty lines here?

2022-09-08 07:09 UTC, siriak commented on src/main/java/com/thealgorithms/strings/Isomorphic.java
> +  }
Please remove the entry point because it's no needed. Tests already test everything

2022-09-08 07:09 UTC, siriak commented on src/main/java/com/thealgorithms/strings/Isomorphic.java
> +    Set<Character> set = new HashSet<Character>();
Please give meaningful names to these variables

2022-09-10 20:11 UTC, Mann-tech13 commented
Pl. check once

2022-09-11 12:29 UTC, siriak requested changes

2022-09-12 20:18 UTC, Mann-tech13 commented on src/main/java/com/thealgorithms/strings/Isomorphic.java
> +    Set<Character> trackUinqueCharacter = new HashSet<Character>();
Changed mapCharactersFrequency to mapCharacters.

2022-09-12 23:29 UTC, siriak approved these changes
Looks good, thanks!

2022-09-12 23:29 UTC, merged