Test for class CountChar.
TheAlgorithms/Java pull request #3334
Opened 2022-10-01 16:49 UTC by ricardo-ramos-moura

### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-09 12:32 UTC, aitorfi commented
The changes you made to the DudeneyNumber class belong to a different PR (#3327) remove those and resolve the merge conflicts please.

2022-10-09 12:36 UTC, aitorfi requested changes
Remove the main method from the CountChar class as the test already demonstrates the algorithm works. Remove the changes made to the DudeneyNumber class as they belong to the PR #3327

2022-10-10 16:35 UTC, aitorfi requested changes
Remove the changes made to the DudeneyNumber class as they belong to the PR #3327 and resolve the merge conflicts please.

2022-10-12 07:04 UTC, aitorfi reviewed
LGTM

2022-10-12 18:40 UTC, siriak commented on src/main/java/com/thealgorithms/maths/DudeneyNumber.java
> +}
```suggestion
}

```

2022-10-12 18:40 UTC, siriak approved these changes
Looks good, thanks!

2022-10-12 18:42 UTC, merged