I added two algorithm related to matrix.
TheAlgorithms/Java pull request #3364
Opened 2022-10-02 18:33 UTC by sadiul-hakim

### **Describe your change:**

- [x ] Add an algorithm?

#### References

### **Checklist:**

- [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ x] This pull request is all my own work -- I have not plagiarized.
- [ x] I know that pull requests will not be merged if they fail the automated tests.
- [ x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x ] All new Java files are placed inside an existing directory.
- [x ] All functions and variable names follow Java naming conventions.

2023-01-09 17:48 UTC, siriak requested changes
The code looks good, could you please add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

2023-01-09 19:03 UTC, sadiul-hakim commented
Thank you for your reply. I'll try to add some test code as soon as possible..

2023-01-10 07:16 UTC, siriak commented on src/main/java/com/thealgorithms/searches/SearchInARowAndColWiseSortedMatrix.java
> +    }
```suggestion

```

2023-01-10 07:16 UTC, siriak commented on src/test/java/com/thealgorithms/searches/TestSearchInARowAndColWiseSortedMatrix.java
> +}
```suggestion
}

```

2023-01-10 07:16 UTC, siriak commented on src/main/java/com/thealgorithms/searches/SearchInARowAndColWiseSortedMatrix.java
> +
```suggestion
                i++;
```

2023-01-10 07:16 UTC, siriak commented on src/main/java/com/thealgorithms/searches/SearchInARowAndColWiseSortedMatrix.java
> +
```suggestion
```

2023-01-10 07:21 UTC, siriak requested changes
The search and its tests looks good. Could you make PrintAMatrixInSpiralOrder return what it intends to print as an array and add tests for that? Or just remove it and I can merge the search. Thanks!

2023-01-14 09:59 UTC, siriak approved these changes
Looks good, thanks!

2023-01-14 10:01 UTC, merged