Created frizzy numbers algorithm
TheAlgorithms/Java pull request #3379
Opened 2022-10-03 12:19 UTC by gitwikc

### **Describe your change:**

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

### **Checklist:**

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ] All new Java files are placed inside an existing directory.
- [ ] All filenames are in all uppercase characters with no spaces or dashes.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2023-01-07 08:56 UTC, siriak requested changes

2023-01-07 08:56 UTC, siriak commented on .gitpod.yml
> +  - init: mvn install -DskipTests=false
The code looks good, but what is this file for?

2023-02-07 15:45 UTC, siddhant2002 commented
Can I work under this issue?

2023-02-08 02:54 UTC, siddhant2002 commented
@siriak Can I work under this issue??

2023-03-01 15:17 UTC, closed without merging