Addition oF Rail Fence Cipher
TheAlgorithms/Java pull request #3385
Opened 2022-10-04 02:56 UTC by hexaorzo

### **Describe your change:**

- [X] Add an algorithm?
Added Rail Fence Cipher

#### References

### **Checklist:**

- [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [X] This pull request is all my own work -- I have not plagiarized.
- [X] I know that pull requests will not be merged if they fail the automated tests.
- [X] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [X] All new Java files are placed inside an existing directory.
- [X] All functions and variable names follow Java naming conventions.

2022-10-04 04:24 UTC, hexaorzo commented
A contribution for Hacktoberfest 2022

2022-11-01 17:47 UTC, siriak requested changes
The code looks good, could you please add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

2022-11-05 11:34 UTC, debasishbsws reviewed
Put a link for reference of this algorithm

2022-11-05 11:34 UTC, debasishbsws commented on src/main/java/com/thealgorithms/ciphers/RailFence.java
> +                System.out.println("default case");
```suggestion
                System.out.println("Invalid Input);
```

2022-11-06 16:52 UTC, hexaorzo commented
Alright I'll implement all the required changes soon.

2023-01-26 00:20 UTC, closed without merging