fix mistake in the heapsort() method and add MaxPriorityQueue.java
TheAlgorithms/Java pull request #3516
Opened 2022-10-12 11:51 UTC by yuhsin7676

### **Describe your change:**

- Fix a bug in the algorithm heapsort() in the MinPriorityQueue.java of com.thealgorithms.datastructures.heaps package. heapsort() method gave an error when size < capacity. Also add MaxPriorityQueue.

#### References

#3515 

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-19 03:28 UTC, debasishbsws reviewed
I think it would be better to use `ArrayList` instead of `int` so the capacity becomes dynamic. and you can also make these using generics, to fit every type of data structure not only int.

2022-10-19 15:30 UTC, siriak requested changes
Please replace `main()`s with JUnit tests

2022-10-19 16:21 UTC, yuhsin7676 commented
> Please replace `main()`s with JUnit tests

OK

2022-10-19 16:52 UTC, debasishbsws commented
I think there are many files that don't have any dedicated test files, rather just a `main()` inside the class.

2022-10-19 17:25 UTC, siriak commented
@debasishbsws that'd be nice!

2022-10-23 05:54 UTC, siriak requested changes

2022-10-23 05:54 UTC, siriak commented on src/test/java/com/thealgorithms/datastructures/lists/CursorLinkedListTest.java
> +    }
This is redundant

2022-10-23 05:54 UTC, siriak commented on src/test/java/com/thealgorithms/datastructures/lists/CursorLinkedListTest.java
> + */
What is that?

2022-10-23 05:54 UTC, siriak commented on nb-configuration.xml
> +</project-shared-configuration>
Please remove this file

2022-10-23 05:54 UTC, siriak commented on pom.xml
> +                    <target>1.8</target>
Revert these changes

2023-01-04 00:19 UTC, closed without merging