Added This Code
TheAlgorithms/Java pull request #3528
Opened 2022-10-13 11:20 UTC by Sinchan26

### **Describe your change:**

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?
- [x] Add a code?
#### References

### **Checklist:**

- [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ x] This pull request is all my own work -- I have not plagiarized.
- [x ] I know that pull requests will not be merged if they fail the automated tests.
- [ x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x ] All new Java files are placed inside an existing directory.
- [x ] All filenames are in all uppercase characters with no spaces or dashes.
- [x ] All functions and variable names follow Java naming conventions.
- [x ] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.
- [x ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-14 07:33 UTC, Sinchan26 commented on src/main/java/com/thealgorithms/dynamicprogramming/ClimbingStairs.java
> + */
O(n)

2022-10-14 09:41 UTC, siriak requested changes
Could you please add some JUnit tests and remove `main()`? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

2022-10-20 19:50 UTC, siriak requested changes

2022-10-20 19:50 UTC, siriak commented on src/main/java/com/thealgorithms/dynamicprogramming/ClimbingStairs.java
> +    }
Please remove this method

2022-10-20 19:50 UTC, siriak commented on src/test/java/com/thealgorithms/dynamicprogramming/ClimbingStairsTest.java
> +    }
Please reference the original method instead of copying it

2023-01-01 00:22 UTC, closed without merging