Added Travelling Salesman Algorithm DP Optimisation using Bit-manipulation
TheAlgorithms/Java pull request #3557
Opened 2022-10-15 18:21 UTC by Rytnix

### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

Issue #3273 

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-16 07:14 UTC, siriak requested changes
Could you put it in dynamic programming module? Bit manipulation is not an algorithm, but rather a technique that can be used to improve runtime characteristics of other algorithms. And please also add JUnit tests and remove main()

2022-10-16 07:23 UTC, Rytnix commented
Ok, sounds good.

2022-10-17 15:23 UTC, Rytnix commented
@siriak Please give it a check. Any more changes?

2022-10-18 18:29 UTC, siriak requested changes

2022-10-18 18:29 UTC, siriak commented on src/main/java/com/thealgorithms/dynamicprogramming/TravellingSalesmanBitManipulation.java
> +    public static int travellingSalesmanBits(int[][] dist,
Please create a wrapper function that creates dp argument for this function and calls it. The caller doesn't need to know about `dp`.

2022-10-18 18:29 UTC, siriak commented on src/main/java/com/thealgorithms/dynamicprogramming/TravellingSalesmanBitManipulation.java
> +            int n, //n is the no of cities we have.
`n` doesn't need to be passed separately because it's `dist.length`

2022-12-22 00:19 UTC, closed without merging