Added new Algorithm
TheAlgorithms/Java pull request #3565
Opened 2022-10-17 04:15 UTC by Mysterious786

### **Describe your change:**

- [ ] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

### **Checklist:**

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] I know that pull requests will not be merged if they fail the automated tests.
- [ ] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [ ] All new Java files are placed inside an existing directory.
- [ ] All filenames are in all uppercase characters with no spaces or dashes.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-17 04:17 UTC, Mysterious786 reviewed
Hamiltonian Cycle

2022-10-17 05:07 UTC, debasishbsws requested changes
Little formatting will look good

2022-10-17 05:07 UTC, debasishbsws commented on src/main/java/com/thealgorithms/backtracking/HamiltonianCycle.java
> +    {
```suggestion
    boolean isSafe(int v, int graph[][], int path[], int pos) {
```

2022-10-17 05:07 UTC, debasishbsws commented on src/main/java/com/thealgorithms/backtracking/HamiltonianCycle.java
> +    {
```suggestion
    boolean hamCycleUtil(int graph[][], int path[], int pos) {
```

2022-10-17 05:07 UTC, debasishbsws commented on src/main/java/com/thealgorithms/backtracking/HamiltonianCycle.java
> +        {
```suggestion
        if (pos == V) {
```

2022-10-17 05:07 UTC, debasishbsws commented on src/main/java/com/thealgorithms/backtracking/HamiltonianCycle.java
> +        {
```suggestion
        for (int v = 1; v < V; v++) {
```

2022-10-17 05:07 UTC, debasishbsws commented on src/main/java/com/thealgorithms/backtracking/HamiltonianCycle.java
> +            {
```suggestion
            if (isSafe(v, graph, path, pos)) {
```

2022-10-17 05:07 UTC, debasishbsws commented on src/main/java/com/thealgorithms/backtracking/HamiltonianCycle.java
> +    {
```suggestion
    int hamCycle(int graph[][]) {
```

2022-10-17 05:07 UTC, debasishbsws commented on src/main/java/com/thealgorithms/backtracking/HamiltonianCycle.java
> +        {
```suggestion
        if (hamCycleUtil(graph, path, 1) == false) {
```

2022-10-17 05:07 UTC, debasishbsws commented on src/main/java/com/thealgorithms/backtracking/HamiltonianCycle.java
> +    {
```suggestion
    void printSolution(int path[]) {
```

2022-10-17 05:07 UTC, debasishbsws commented on src/main/java/com/thealgorithms/backtracking/HamiltonianCycle.java
> +    {
```suggestion
    public static void main(String args[]) {
```

2022-10-17 05:07 UTC, debasishbsws commented on src/main/java/com/thealgorithms/backtracking/HamiltonianCycle.java
> +package com.thealgorithms.backtracking;
Add comments about the algorithm, and put some links where people can read and know about the algorithm

2022-10-17 06:05 UTC, Mysterious786 commented
Thanks for formatting suggestion

2022-10-17 06:08 UTC, debasishbsws approved these changes
Looks Good

2022-10-17 06:08 UTC, Mysterious786 commented on src/main/java/com/thealgorithms/backtracking/HamiltonianCycle.java
> +
https://www.geeksforgeeks.org/hamiltonian-cycle-backtracking-6/

2022-10-22 19:18 UTC, siriak requested changes
The code looks good, could you please add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

2022-12-17 12:57 UTC, raisahab9125 commented
lol its annoying     **think i  got stucked** 
@BurkHufnagel #3566 #3566 #3620 #3797

2023-01-25 00:21 UTC, closed without merging