Reduced time complexity for reversing a string
TheAlgorithms/Java pull request #3581
Opened 2022-10-17 21:57 UTC by pritam-dash

Added a third way of reversing a string, which reduces the time complexity of the code.

### **Describe your change:**

- [x] Add an algorithm?
- [x] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [ ] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [ ] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-18 06:31 UTC, Teuton-Roy approved these changes
Just need little bit of formating

2022-10-18 06:31 UTC, Teuton-Roy commented on src/main/java/com/thealgorithms/strings/ReverseString.java
> +        {
```suggestion
        for(int i=0, j=len-1; i<len/2; i++, j--) {
```

2022-10-18 06:31 UTC, Teuton-Roy commented on src/main/java/com/thealgorithms/strings/ReverseString.java
> +        return new String(s2+str.charAt(len/2)+s1);
```suggestion
        if(len%2 == 0)
            return new String(s2 + s1);
        else
            return new String(s2 + str.charAt(len/2) + s1);
```

2022-10-19 17:32 UTC, siriak requested changes
The code looks good, could you please add some automated tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

2022-10-19 18:35 UTC, pritam-dash commented
Can you kindly elaborate on the upgrades that you are looking for?
It would help me to further integrate the desired tests with curated results.

2022-10-20 19:47 UTC, siriak commented
JUnit tests https://www.tutorialspoint.com/junit/junit_test_framework.htm

2022-12-22 00:19 UTC, closed without merging