Algo for Two's Complement of any Binary String
TheAlgorithms/Java pull request #3620
Opened 2022-10-21 18:23 UTC by atharva20-coder

### **Describe your change:**

- [x] Add an algorithm?
- [ ] Fix a bug or typo in an existing algorithm?
- [ ] Documentation change?

#### References

### **Checklist:**

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-21 18:26 UTC, atharva20-coder commented
@siriak @yanglbme Please check the PR

2022-10-22 15:23 UTC, atharva20-coder commented
@siriak Please review this PR

2022-11-16 08:04 UTC, debasishbsws commented on src/main/java/com/thealgorithms/conversions/TwosComplementOfBinaryString.java
> +
```suggestion
		for (int i = n-1 ; i >= 0 ; i--){
			if (str.charAt(i) == '1'){
				break;
			}
		}
```

2022-11-16 08:05 UTC, debasishbsws commented on src/main/java/com/thealgorithms/conversions/TwosComplementOfBinaryString.java
> +			return "1" + str;
```suggestion
		if (i == -1){
			return "1" + str;
		}
```

2022-11-16 08:06 UTC, debasishbsws requested changes

2022-11-16 08:06 UTC, debasishbsws commented on src/main/java/com/thealgorithms/conversions/TwosComplementOfBinaryString.java
> +}
Remove main method and ad some jUnit test

2022-12-25 00:21 UTC, closed without merging