RadixSort fixed bug, adding test file for it
TheAlgorithms/Java pull request #3629
Opened 2022-10-22 14:20 UTC by Teuton-Roy

- Fix one bug; sorting doesn't work for empty array.
- Add test cases for Radix_sort.

- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-22 16:26 UTC, debasishbsws approved these changes
Everything looks good.

2022-10-22 19:02 UTC, siriak requested changes

2022-10-22 19:02 UTC, siriak commented on src/main/java/com/thealgorithms/sorts/RadixSort.java
> +        for (int i = 0; i < arr.length; i++) {
Please throw an exception if array is empty

2022-10-22 19:02 UTC, siriak commented on src/main/java/com/thealgorithms/sorts/RadixSort.java
>      }
Please remove `main()`

2022-10-26 07:25 UTC, siriak requested changes
The code looks good, please fix PR checks

2022-10-27 04:14 UTC, debasishbsws requested changes

2022-10-27 04:14 UTC, debasishbsws commented on src/main/java/com/thealgorithms/sorts/RadixSort.java
> +
```suggestion
    }
```

You Have Missed a Curly Braces here

2022-10-29 12:51 UTC, debasishbsws submitted a review, later dismissed

2022-10-31 19:49 UTC, siriak requested changes

2022-10-31 19:49 UTC, siriak commented on src/main/java/com/thealgorithms/sorts/RadixSort.java
> +    public void radixSort(int[] arr) {
Please handle empty array. It's already sorted

2022-12-11 00:22 UTC, closed without merging