Added another function to PerfectCube.java
TheAlgorithms/Java pull request #3655
Opened 2022-10-25 10:55 UTC by TaranjeetSinghKalsi

Added another function to PerfectCube.java and fixed a testing mistake in line number 9

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] I know that pull requests will not be merged if they fail the automated tests.
- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.
- [x] All new Java files are placed inside an existing directory.
- [x] All filenames are in all uppercase characters with no spaces or dashes.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.

2022-10-25 12:04 UTC, siriak requested changes
The code looks good, could you please add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

2022-10-27 18:58 UTC, TaranjeetSinghKalsi reviewed
Added Junit Tests. Kindly review it.

2022-10-27 19:13 UTC, debasishbsws requested changes

2022-10-27 19:13 UTC, debasishbsws commented on src/main/java/com/thealgorithms/maths/PerfectCube.java
>      }
remove the main function

2022-10-27 19:15 UTC, TaranjeetSinghKalsi commented on src/main/java/com/thealgorithms/maths/PerfectCube.java
>      }
done

2022-10-29 06:03 UTC, siriak approved these changes
Looks good, thanks!

2022-10-29 06:04 UTC, siriak commented
@debasishbsws please review

2022-10-29 06:26 UTC, debasishbsws approved these changes
Looks good

2022-10-29 06:27 UTC, merged