Added Test cases for egg droppings
TheAlgorithms/Java pull request #3687
Opened 2022-10-26 19:02 UTC by naanagon

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2022-10-26 19:04 UTC, naanagon commented
@siriak , @yanglbme Test cases passed. Can you please take a look..?

2022-10-27 11:07 UTC, naanagon commented
@siriak , @yanglbme - could you please review, build is green now.

2022-10-27 12:44 UTC, yanglbme approved these changes

2022-10-27 12:46 UTC, yanglbme requested changes

2022-10-27 12:46 UTC, yanglbme commented on src/test/java/com/thealgorithms/dynamicprogramming/EgsDroppingTest.java
> +public class EgsDroppingTest {
```suggestion
public class EggDroppingTest {
```

please rename the class and java file

2022-10-27 16:43 UTC, naanagon commented on src/test/java/com/thealgorithms/dynamicprogramming/EgsDroppingTest.java
> +public class EgsDroppingTest {
Done

2022-10-27 17:52 UTC, siriak approved these changes
Looks good, thanks!

2022-10-27 17:52 UTC, merged