Create Valid_Parentheses.java
TheAlgorithms/Java pull request #3689
Opened 2022-10-26 20:46 UTC by adjamalbek

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2022-10-27 20:43 UTC, skinox commented
Can you reply to this, since I don't really understand how it works, there are a lot of pull requests, however only random one's are chosen and I see there are some pull requests that are 20+ days old/

2022-10-27 21:53 UTC, adjamalbek reviewed
updated the class

2022-10-27 22:00 UTC, adjamalbek reviewed
updated class

2022-10-29 10:44 UTC, debasishbsws reviewed
Add some JUnit tests

2022-10-29 11:30 UTC, adjamalbek commented
> Add some JUnit tests

I did, https://github.com/TheAlgorithms/Java/pull/3709 2 days ago, for all the commits

2022-10-30 04:02 UTC, debasishbsws requested changes
Build failing, need PAckage declaration

2022-10-30 04:02 UTC, debasishbsws commented on src/main/java/com/thealgorithms/strings/ValidParentheses.java
> +//        Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.
```suggestion
package com.thealgorithms.strings;
//        Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.
```

2022-10-30 19:44 UTC, adjamalbek commented
All the errors are fixed

2022-10-30 19:52 UTC, debasishbsws commented
unable to build.

2022-10-30 20:38 UTC, adjamalbek commented
Sorry, I didn't put last commit

2022-10-31 10:20 UTC, adjamalbek commented
Requesting review from @siriak and @yanglbme and @debasishbsws for approval and merging.

2022-10-31 18:08 UTC, adjamalbek reviewed
updated

2022-10-31 18:08 UTC, siriak approved these changes
Looks good, thanks!

2022-10-31 18:09 UTC, siriak commented
@debasishbsws please review again

2022-11-01 05:48 UTC, debasishbsws submitted a review, later dismissed
Nice, thank you for contributing

2022-11-01 17:25 UTC, siriak approved these changes

2022-11-01 17:26 UTC, merged