Create Sort_Sentence_StringTest
TheAlgorithms/Java pull request #3711
Opened 2022-10-27 21:24 UTC by adjamalbek

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2022-10-27 22:18 UTC, adjamalbek commented
Added Junit Tests. Kindly review it @siriak @yanglbme @debasishbsws

2022-10-29 06:49 UTC, siriak commented on DIRECTORY.md
>    * test
```suggestion
  * test
    * java
      * com
        * thealgorithms
```

2022-10-29 06:50 UTC, debasishbsws requested changes
File name doesn't follow java convention of using pascal case as class names.

2022-10-29 07:06 UTC, siriak requested changes
Please make the same changes as in your different PR

2022-10-29 08:20 UTC, adjamalbek reviewed
change the class name

2022-10-29 08:29 UTC, adjamalbek reviewed
reviewed

2022-10-29 08:41 UTC, adjamalbek reviewed
updated

2022-10-29 11:34 UTC, debasishbsws commented
Ok, as I can see you have made a PR for the algorithm and made another PR for the test cases. It would be good to put those in a single PR. Because after seeing this PR we _can't_ find the algorithm present, and on the algorithm's PR we are asking to add some JUnit tests.

2022-10-29 11:38 UTC, adjamalbek commented
> Ok, as I can see you have made a PR for the algorithm and made another PR for the test cases. It would be good to put those in a single PR. Because after seeing this PR we _can't_ find the algorithm present, and on the algorithm's PR we are asking to add some JUnit tests.

The reason for this is, I firstly submit the src code, and forgot about the test cases, only after reading comment and have added test cases for all the problems and renamed all the classes by following rules, moreover it's my first experience in GIT, please don't judge strictly, next time I will be more careful and submit everything in a single PR. Thank you

2022-10-30 07:14 UTC, siriak commented
You can just merge patch-8 branch into patch-4 and the changes will be reflected in the corresponding PR. We do not add algorithms without/separately from tests

2022-10-30 20:37 UTC, closed without merging