Create Plus_oneTest
TheAlgorithms/Java pull request #3712
Opened 2022-10-27 21:34 UTC by adjamalbek

added j-unit test for problem

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2022-10-27 22:17 UTC, adjamalbek commented
Added Junit Tests. Kindly review it @siriak @yanglbme @debasishbsws

2022-10-29 06:10 UTC, siriak requested changes
Please add .java extension to your file, use PascalCase or camelCase as appropriate, and fix PR checks

2022-10-29 08:31 UTC, adjamalbek reviewed
updated

2022-10-29 18:27 UTC, debasishbsws requested changes
The variables and method name should be in camelCase

2022-10-29 18:27 UTC, debasishbsws commented on src/test/java/com/thealgorithms/maths/PlusOneTest.java
> +}
```suggestion
int[] intArray1 = new int[]{ 1,2,4 }; 
int[] intArray2 = new int[]{ 4,3,2,2 }; 
int[] intArray3 = new int[]{ 1,0 }; 

int[] intArray1Test = new int[]{ 1,2,3 }; 
int[] intArray2Test = new int[]{ 4,3,2,1 }; 
int[] intArray3Test = new int[]{ 9 }; 

    @Test
    void testOne() {
        assertEquals(intArray1, PlusOne.plusOne(intArray1Test));
    }
    @Test
    void testTwo() {
        assertEquals(intArray2, PlusOne.plusOne(intArray2Test));
    }
    @Test
    void testThree() {
        assertEquals(intArray3, PlusOne.plusOne(intArray3Test));
    }
}
```

2022-10-30 20:37 UTC, closed without merging