added BogoSortTest
TheAlgorithms/Java pull request #3716
Opened 2022-10-28 08:02 UTC by hyeonmin2

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2022-10-29 06:00 UTC, siriak requested changes

2022-10-29 06:00 UTC, siriak commented on src/test/java/com/thealgorithms/sorts/BogoSortTest.java
> +    public void bogoSortEmptyArray() {
Please convert tabs to spaces

2022-10-29 15:39 UTC, hyeonmin2 commented on src/test/java/com/thealgorithms/sorts/BogoSortTest.java
> +    public void bogoSortEmptyArray() {
I converted it

2022-10-31 19:51 UTC, siriak approved these changes
Looks good, thanks!

2022-10-31 19:52 UTC, merged