Fibonacci optimized using binet's formula
TheAlgorithms/Java pull request #3728
Opened 2022-10-28 21:06 UTC by Aayush2111

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2022-10-29 11:10 UTC, debasishbsws requested changes
And I think as input became large output will not fit inside int anymore. think about it

2022-10-29 11:10 UTC, debasishbsws commented on src/main/java/com/thealgorithms/dynamicprogramming/Fibonacci.java
>       * @author Shoaib Rayeen (https://github.com/shoaibrayeen)
There are comments about the method that was implemented as an optimized Fibonacci.

2022-10-29 11:10 UTC, debasishbsws commented on src/main/java/com/thealgorithms/dynamicprogramming/Fibonacci.java
> +        return (int) (Math.pow(((1 + Math.sqrt(5)) / 2), n) / Math.sqrt(5));
make another methods `fibBinet(int n)` and put this there and also put comments prior to that about explaining the Binet or put a link where people can find them.

2022-10-29 22:51 UTC, Aayush2111 commented
Can you review again?
is it okay?

2022-10-30 03:55 UTC, debasishbsws approved these changes
Looks good

2022-10-30 03:56 UTC, merged