Check Whether a NO. is Power of Two or Not
TheAlgorithms/Java pull request #3746
Opened 2022-10-30 16:31 UTC by hacreating

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2022-11-06 11:56 UTC, debasishbsws commented
Don't know if is it be concider an Algorithm or not. Could you put some links about this approach? 
It is a clever way to find if the number is a power of 2 or not.🤔

2022-11-06 11:58 UTC, debasishbsws commented
You should put the file inside `src/main/java/com/thealgorithm/others`

2022-11-07 17:56 UTC, siriak requested changes
Put it in a folder and add tests

2022-11-14 03:31 UTC, madanrgowda approved these changes

2022-12-23 00:19 UTC, closed without merging