Patch 2
TheAlgorithms/Java pull request #3748
Opened 2022-10-30 19:45 UTC by adjamalbek

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2022-10-30 19:46 UTC, adjamalbek commented
all the errors were fixed

2022-10-30 19:59 UTC, debasishbsws requested changes

2022-10-30 19:59 UTC, debasishbsws commented on src/main/java/com/thealgorithms/strings/SortSentenceString.java
> +        for(String word:arr_1)
```suggestion
        String[] arr1 = new StringBuilder(s).reverse().toString().split(" ");
        Arrays.sort(arr1);
        for(String word:arr1)
```

2022-10-31 10:20 UTC, adjamalbek commented
Requesting review from @siriak and @yanglbme and @debasishbsws for approval and merging.

2022-10-31 17:58 UTC, siriak commented
It's not an algorithm in a sense that there's no problem in sorting something with a built-in function

2022-10-31 17:58 UTC, closed without merging