Update maths/Volume.java
TheAlgorithms/Java pull request #3773
Opened 2022-11-19 09:25 UTC by Harpia-Vieillot

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2022-11-19 11:28 UTC, siriak requested changes
Looks good. Please fix the build check.

2022-11-19 15:05 UTC, debasishbsws commented on src/test/java/com/thealgorithms/maths/VolumeTest.java
> +        assertTrue(volumeEllipsoid(2, 5, 7) == 11.666666666666666);
```suggestion
        assertTrue(Volume.volumeEllipsoid(2, 5, 7) == 11.666666666666666);
```

2022-11-19 15:05 UTC, debasishbsws requested changes
Ellipsoid Volume formula is wrong
https://www.omnicalculator.com/math/ellipsoid-volume#:~:text=Volume%20%3D%204/3%20*%20%CF%80%20*%20A%20*%20B%20*%20C%2C
  
Check this, change the code, and test accordingly.

2022-11-19 15:05 UTC, debasishbsws commented on src/test/java/com/thealgorithms/maths/VolumeTest.java
> +        assertTrue(volumeEllipsoid(2, 5, 7) == 11.666666666666666);
```suggestion
        assertTrue(Volume.volumeEllipsoid(2, 5, 7) == 11.666666666666666);
```

2022-11-20 14:42 UTC, Harpia-Vieillot commented on src/test/java/com/thealgorithms/maths/VolumeTest.java
> +        assertTrue(volumeEllipsoid(2, 5, 7) == 11.666666666666666);
> This should fix the build fail

It isn't working bro...

2022-11-20 14:42 UTC, Harpia-Vieillot commented on src/test/java/com/thealgorithms/maths/VolumeTest.java
> +        assertTrue(volumeEllipsoid(2, 5, 7) == 11.666666666666666);
> This should fix the build fail

It isn't working.

2022-11-22 07:19 UTC, Harpia-Vieillot commented
> Looks good. Please fix the build check.

I am unable to find where the build check is failing.

2022-12-24 16:01 UTC, siriak commented
It says
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/Java/Java/src/main/java/com/thealgorithms/maths/Volume.java:[98,63] illegal start of type
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.021 s
[INFO] Finished at: 2022-11-20T14:33:13Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project Java: Compilation failure
Error:  /home/runner/work/Java/Java/src/main/java/com/thealgorithms/maths/Volume.java:[98,63] illegal start of type
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error: Process completed with exit code 1.

2022-12-27 15:56 UTC, closed without merging