add the conway sequence
TheAlgorithms/Java pull request #3807
Opened 2023-01-09 09:09 UTC by eloibru

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-01-09 17:46 UTC, siriak requested changes
The code looks good, could you please add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

2023-01-09 21:32 UTC, eloibru commented
Done, I've added a few tests.

2023-01-10 07:28 UTC, siriak requested changes

2023-01-10 07:28 UTC, siriak commented on src/main/java/com/thealgorithms/others/Conway.java
> +    * */
```suggestion

    /*
    * This class will generate the conway sequence also known as the look and say sequence.
    * To generate a member of the sequence from the previous member, read off the digits of the previous member, counting the number of digits in groups of the same digit. For example:
    *1 is read off as "one 1" or 11.
    *11 is read off as "two 1s" or 21.
    *21 is read off as "one 2, one 1" or 1211.
    *1211 is read off as "one 1, one 2, two 1s" or 111221.
    *111221 is read off as "three 1s, two 2s, one 1" or 312211.
    * https://en.wikipedia.org/wiki/Look-and-say_sequence
    * */
```

2023-01-10 07:28 UTC, siriak commented on src/main/java/com/thealgorithms/others/Conway.java
> +    }
```suggestion
```

2023-01-10 07:28 UTC, siriak commented on src/main/java/com/thealgorithms/others/Conway.java
> +
```suggestion
```

2023-01-10 07:28 UTC, siriak commented on src/main/java/com/thealgorithms/others/Conway.java
> +
```suggestion
```

2023-01-10 07:28 UTC, siriak commented on src/main/java/com/thealgorithms/others/Conway.java
> +            }
```suggestion
            originalString = generateNextElement(originalString);
            numbers.add(originalString);
        }
```

2023-01-10 07:28 UTC, siriak commented on src/test/java/com/thealgorithms/others/ConwayTest.java
> +
```suggestion
```

2023-01-10 07:28 UTC, siriak commented on src/test/java/com/thealgorithms/others/ConwayTest.java
> +        assertTrue(Conway.generateList("1").contains("1321132132211331121321231231121113112221121321132122311211131122211211131221131211132221121321132132212321121113121112133221123113112221131112311
Please check a specific element of the sequence. For example, the last one

2023-01-10 07:28 UTC, siriak commented on src/main/java/com/thealgorithms/others/Conway.java
> +        for(int i=0; i<20; i++) {
What is `20`? Please make this a function parameter

2023-01-14 10:18 UTC, siriak commented on src/main/java/com/thealgorithms/others/Conway.java
> +    }
```suggestion
```

2023-01-14 10:19 UTC, siriak approved these changes
Looks good, thanks!

2023-01-14 10:22 UTC, merged