Add conway sequence reverse
TheAlgorithms/Java pull request #3851
Opened 2023-01-16 08:31 UTC by eloibru

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-01-16 11:44 UTC, siriak commented on src/main/java/com/thealgorithms/others/ConwayReverse.java
> +
```suggestion
```

2023-01-16 11:44 UTC, siriak commented on src/main/java/com/thealgorithms/others/ConwayReverse.java
> +    private static final int MAX_ITERATION_ALLOWED = 5;
```suggestion
```

2023-01-16 11:46 UTC, siriak approved these changes
Looks good, thanks!

2023-01-16 11:47 UTC, siriak requested changes

2023-01-16 11:47 UTC, siriak commented on src/main/java/com/thealgorithms/others/ConwayReverse.java
> +        while (s1.length() > 1 && count < MAX_ITERATION_ALLOWED && s1.length()%2==0);
I've removed main because it's not needed. Could you add MAX_ITERATIONS_ALLOWED to method parameters?

2023-01-26 11:14 UTC, tangorishi approved these changes

2023-03-03 16:52 UTC, siddhant2002 commented
I can work under this issue?

2023-04-11 00:19 UTC, closed without merging