Adding Kosaraju Algorithm
TheAlgorithms/Java pull request #3859
Opened 2023-01-17 02:49 UTC by shivu2002a

- [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ x] This pull request is all my own work -- I have not plagiarized it.
- [ x] All filenames are in PascalCase.
- [ x] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-01-17 20:09 UTC, siriak requested changes
The code looks good, could you please add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

2023-02-04 02:39 UTC, shivu2002a commented
Hi, @siriak, I've added test cases also.

2023-02-04 07:49 UTC, siriak commented on src/test/java/com/thealgorithms/datastructures/graphs/KosarajuTest.java
> +            0, 1, 2, 0
```suggestion
            0, 1, 2
```

2023-02-04 07:49 UTC, siriak commented on src/main/java/com/thealgorithms/datastructures/graphs/Kosaraju.java
> +        }
Maybe you could extract it into a method called `sortEdgesByLowestFinishTime`?

2023-02-04 07:49 UTC, siriak commented on src/main/java/com/thealgorithms/datastructures/graphs/Kosaraju.java
> +        }
And extract the methods below too

2023-02-06 11:41 UTC, shivu2002a commented
@siriak Suggested changes have been implemented.

2023-02-07 06:46 UTC, siriak requested changes

2023-02-07 06:46 UTC, siriak commented on src/main/java/com/thealgorithms/datastructures/graphs/Kosaraju.java
>      public static void main(String[] args) {
Please remove main, it's redundant because there are tests checking that the algorithm works

2023-02-07 06:46 UTC, siriak commented on src/main/java/com/thealgorithms/datastructures/graphs/Kosaraju.java
> +        return sccsList;
Please remove the comments, function names already explain the algorithm

2023-02-07 06:46 UTC, siriak commented on src/main/java/com/thealgorithms/datastructures/graphs/Kosaraju.java
> +        findSCCs(v, transposeGraph);
Please write in full findStronglyConnectedComponents

2023-02-07 06:46 UTC, siriak commented on src/test/java/com/thealgorithms/datastructures/graphs/KosarajuTest.java
> +        System.out.println(actualResult);
```suggestion
```

2023-02-07 07:10 UTC, shivu2002a commented
@siriak Done!!

2023-02-08 18:04 UTC, siriak approved these changes
Looks good, thanks!

2023-02-08 18:05 UTC, merged