Added the String Compression Algorithm #3911
TheAlgorithms/Java pull request #3916
Opened 2023-03-09 23:17 UTC by Swarga-codes

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-03-10 14:38 UTC, Swarga-codes commented
Should I remove the main function from the code and make a test file in the test folder for this particular algorithm?

2023-03-14 03:19 UTC, Swarga-codes commented
@siriak  I made the necessary changes as u told on the PR, the changes include:

Reduce the size of code by dividing the code into smaller functions
Removed unnecessary comments
Removed the main
Included some Junit test cases for the code which you can access in the tests folder
Can you please check ?

2023-03-14 07:53 UTC, siriak requested changes

2023-03-14 07:53 UTC, siriak commented on src/main/java/com/thealgorithms/strings/StringCompression.java
> +  public static String checkCount(String res, int count, char[] ch, int i) {
This funciton only uses `ch[i]`, so you could only pass the current character to it and not the whole array

2023-03-14 07:53 UTC, siriak commented on src/main/java/com/thealgorithms/strings/StringCompression.java
> +    String res = "";
```suggestion
    String compressedString = "";
```

2023-03-14 07:53 UTC, siriak commented on src/main/java/com/thealgorithms/strings/StringCompression.java
> +  public static String compress(char[] ch) {
```suggestion
  public static String compress(String input) {
```

2023-03-14 07:53 UTC, siriak commented on src/main/java/com/thealgorithms/strings/StringCompression.java
> +/*  Link to the problem : https://leetcode.com/problems/string-compression/description/
Please link to Wikipedia instead

2023-03-14 07:53 UTC, siriak commented on src/main/java/com/thealgorithms/strings/StringCompression.java
> +    }
```suggestion
```

2023-03-14 07:53 UTC, siriak commented on src/main/java/com/thealgorithms/strings/StringCompression.java
> +        res = checkCount(res, count, ch, i);
Please provide a more descriptive name instead of `checkCount` because I'd expect `check...` function to throw an error and to not return a string

2023-03-14 07:53 UTC, siriak commented on src/test/java/com/thealgorithms/strings/StringCompressionTest.java
> +    public void StringCompressionTest(){
Could you make it a parameterized test?

2023-03-16 17:13 UTC, Swarga-codes commented
I made the necessary changes as per your instructions, that is:
1) Changed the parameters for the checkCount function and passed the particular character rather than passing the entire array.
2) Changed the name of the resulting string "res" to "compressedString".
3) Changed the type of input from a character array to a string named "input".
4) Changed the reference link from Leetcode to Wikipedia.
5) Removed the unnecessary loop at the end as suggested.
6) Changed the name of checkCount function to a more descriptive name, that is, appendCount, since we are appending the count to the resulting string.
7) Changed the Junit test cases to parameterized Junit tests.
Can you please check?

2023-03-19 07:49 UTC, siriak approved these changes
Looks good, thanks!

2023-03-19 07:51 UTC, merged