Add MaximumSubarrayAlgorithm
TheAlgorithms/Java pull request #4158
Opened 2023-04-19 20:04 UTC by klevinazeraj

- [x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ x] This pull request is all my own work -- I have not plagiarized it.
- [x ] All filenames are in PascalCase.
- [x ] All functions and variable names follow Java naming conventions.
- [x ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-04-20 08:53 UTC, siriak commented
This algorithm is implemented here https://github.com/TheAlgorithms/Java/blob/1551b8f50ba485b5a7d34fe9ed1fbf650134fb9f/src/main/java/com/thealgorithms/dynamicprogramming/KadaneAlgorithm.java
Please make desired changes there

2023-04-20 14:09 UTC, klevinazeraj commented
> This algorithm is implemented here https://github.com/TheAlgorithms/Java/blob/1551b8f50ba485b5a7d34fe9ed1fbf650134fb9f/src/main/java/com/thealgorithms/dynamicprogramming/KadaneAlgorithm.java
> Please make desired changes there

This algorithm falls under divide and conquer category, are you sure?

2023-04-21 08:38 UTC, siriak commented
Why is it divide and conquer? I'd say that it's dynamic programming because it just goes over elements 1 by 1 and doesn't explicitly divide input in parts.

2023-04-21 15:29 UTC, klevinazeraj commented
It cuts down the array in half's the same way merge sort does and then finds the maximum subarray for each of those subarrays and it returns the greatest one. Here is a great video to visualize the process. https://youtu.be/3GD-3UZGsVI

2023-04-22 07:46 UTC, siriak commented
I see, it differs from what've linked to

2023-04-22 07:50 UTC, siriak requested changes

2023-04-22 07:50 UTC, siriak commented on src/main/java/com/thealgorithms/divideandconquer/MaximumSubarrayAlgorithm.java
> +    public static int[] findMaximumSubarray(int[] A, int low, int high) {
Please add a public function `int[] findMaximumSubarray(int[] array)` that only accepts array and returns only starting and ending indexes of the maximum subarray. And make these functions private, as those are implementation and not contract. They can be tested through the public function.

2023-05-26 07:26 UTC, siddhant2002 commented
Can I work on this issue?

2023-06-10 18:28 UTC, siddhant2002 commented
ok

2023-07-18 00:40 UTC, closed without merging