Adding SetBit to bitmanipulation
TheAlgorithms/Java pull request #4348
Opened 2023-09-02 09:11 UTC by lukasb1b

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-09-02 17:38 UTC, siriak requested changes
Please fix PR checks

2023-09-02 22:19 UTC, lukasb1b commented
Im sorry im new to github and I accedently resubmittet it. Can you explain to me how I need to change it?

2023-09-03 13:21 UTC, siriak commented
You can find problems here https://github.com/TheAlgorithms/Java/actions/runs/6060803308/job/16453536079?pr=4348
These are indentation and spaces
![image](https://github.com/TheAlgorithms/Java/assets/29201949/ebe91d6d-15b5-480c-8325-29e525c7542f)

2023-09-05 14:15 UTC, lukasb1b commented
I now changed the formatting i hope thats it

2023-09-05 20:16 UTC, siriak commented
Not yet :) See output of the failing job

2023-09-06 14:41 UTC, siriak commented on src/test/java/com/thealgorithms/bitmanipulation/SetBit.java
> +
```suggestion
```

2023-09-06 14:44 UTC, siriak approved these changes
Looks good, thanks!

2023-09-06 14:46 UTC, merged