Added koko eating bananas problem (binary search on answer)
TheAlgorithms/Java pull request #4371
Opened 2023-09-12 18:10 UTC by Atreya-112

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-09-12 20:29 UTC, vil02 requested changes
Please do not use the `main` method. I think in this case, `BinarySearchOnAnswer` can be a _utility class_. And please add unit tests of your class. I think a good examples to look at are [`Factorial`](https://github.com/TheAlgorithms/Java/blob/34cf6dab28ee2271fbf228d345bcf14db85c211c/src/main/java/com/thealgorithms/maths/Factorial.java) and [`FactorialTest`](https://github.com/TheAlgorithms/Java/blob/34cf6dab28ee2271fbf228d345bcf14db85c211c/src/test/java/com/thealgorithms/maths/FactorialTest.java).

2023-09-12 20:29 UTC, vil02 commented on src/main/java/com/thealgorithms/binarysearchonanswer/BinarySearchOnAnswer.java
> +}
```suggestion
}

```
This should fix the failing `clang-format` job.

2023-09-12 20:35 UTC, BamaCharanChhandogi commented on src/main/java/com/thealgorithms/binarysearchonanswer/BinarySearchOnAnswer.java
> + leetcode link : https://leetcode.com/problems/koko-eating-bananas/descripti
check leetcode link

2023-09-13 08:43 UTC, siriak commented
We do not add leetcode problems, as they are usually just a variation of a known technique. Those basic techniques are already implemented separately

2023-09-13 08:43 UTC, closed without merging