FourSumProblem #4374
TheAlgorithms/Java pull request #4383
Opened 2023-09-20 05:35 UTC by Shonu72

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-09-20 07:28 UTC, BamaCharanChhandogi requested changes
Add all possible test cases.👍

2023-09-20 07:28 UTC, BamaCharanChhandogi commented on src/main/java/com/thealgorithms/misc/FourSumProblem.java
> +        for (int i = 0; i < n; i++) {
This approach does not have a good time complexity. Try to achieve better time complexity

2023-09-20 15:56 UTC, vil02 commented
Is it a duplicate of #4375 and #4377?

2023-09-27 03:40 UTC, BamaCharanChhandogi commented
I am closing this PR.

2023-09-27 03:40 UTC, closed without merging