#4382 Bug Fix
TheAlgorithms/Java pull request #4384
Opened 2023-09-20 07:10 UTC by govardhanshah456

Fixed The Bug for the Test Case mentioned in linked Issue as well as made code more readable

2023-09-20 15:33 UTC, vil02 requested changes
@govardhanshah456 thanks for working the issue #4382. I really like that you decided to rename the `p1` and `p2` member variables.

2023-09-20 16:56 UTC, govardhanshah456 commented
Hey, i have made requested changes, please have a look into it.

2023-09-20 17:13 UTC, govardhanshah456 commented on src/main/java/com/thealgorithms/misc/MedianOfRunningArray.java
>      public static void main(String[] args) {
Hey, i have made the required changes.

2023-09-20 18:59 UTC, vil02 requested changes
As a quick bug fix it looks really good. I suggest to add some tests (it is good to have a test case causing the original bug). You can use the `commit suggestion` button.

I know that this is out of scope for this PR, but I think it would be reasonable to make the `MedianOfRunningArray` a _generic type_, so one could compute a median of integers (and the result would be an integer), doubles (and the result would be a double) etc. @govardhanshah456 would you like to work on such an issue?

2023-09-20 18:59 UTC, vil02 commented on src/main/java/com/thealgorithms/misc/MedianOfRunningArray.java
> +    public Double median() {
Is there a reason why `Double` (**not** `double`) is used here?

```suggestion
    public double median() {
```

2023-09-20 18:59 UTC, vil02 commented on src/main/java/com/thealgorithms/misc/MedianOfRunningArray.java
> +        return maxHeap.size() > minHeap.size() ? maxHeap.peek() * 1.0 : minHeap.peek() * 1.0;
I think one can simplify the logic a bit

```suggestion
        if (maxHeap.isEmpty() && minHeap.isEmpty()) {
            throw new IllegalArgumentException("Enter at least 1 element, Median of empty list is not defined!");
        }

        if (maxHeap.size() == minHeap.size()) {
            return (maxHeap.peek() + minHeap.peek()) / 2.0;
        }
        return maxHeap.size() > minHeap.size() ? maxHeap.peek() * 1.0 : minHeap.peek() * 1.0;
```

2023-09-20 18:59 UTC, vil02 commented on src/test/java/com/thealgorithms/misc/MedianOfRunningArrayTest.java
> +
```suggestion

    @Test
    public void testWithDuplicateValuesB() {
        MedianOfRunningArray stream = new MedianOfRunningArray();
        stream.insert(10);
        stream.insert(20);
        stream.insert(10);
        stream.insert(10);
        stream.insert(20);
        stream.insert(0);
        stream.insert(50);
        assertEquals(10, stream.median());
    }

```

2023-09-20 18:59 UTC, vil02 commented on src/test/java/com/thealgorithms/misc/MedianOfRunningArrayTest.java
> +}
```suggestion

    @Test
    public void testWithThreeValuesInDescendingOrder() {
        MedianOfRunningArray stream = new MedianOfRunningArray();
        stream.insert(30);
        stream.insert(20);
        stream.insert(10);
        assertEquals(20.0, stream.median());
    }

    @Test
    public void testWithThreeValuesInOrder() {
        MedianOfRunningArray stream = new MedianOfRunningArray();
        stream.insert(10);
        stream.insert(20);
        stream.insert(30);
        assertEquals(20.0, stream.median());
    }

    @Test
    public void testWithThreeValuesNotInOrderA() {
        MedianOfRunningArray stream = new MedianOfRunningArray();
        stream.insert(30);
        stream.insert(10);
        stream.insert(20);
        assertEquals(20.0, stream.median());
    }

    @Test
    public void testWithThreeValuesNotInOrderB() {
        MedianOfRunningArray stream = new MedianOfRunningArray();
        stream.insert(20);
        stream.insert(10);
        stream.insert(30);
        assertEquals(20.0, stream.median());
    }
}
```

2023-09-21 05:54 UTC, govardhanshah456 commented
Hey, as you said its out of scope for this PR, what we can do instead is we can make new enhancement issue of making Median Generic and then work on it, that would appear more appropriate, and yes median would always be double for instance, (1,2) median would be (1+2)/2 which is double although input is int array.

2023-09-21 06:02 UTC, vil02 approved these changes
Awesome @govardhanshah456!

Closes #4382.

2023-09-21 06:05 UTC, merged