Made Median Generic
TheAlgorithms/Java pull request #4392
Opened 2023-09-21 08:05 UTC by govardhanshah456

2023-09-21 09:37 UTC, govardhanshah456 commented
@vil02 Hey, i did some changes according to my knowledge of generics. You can check it.

2023-09-21 20:29 UTC, vil02 requested changes

2023-09-21 20:29 UTC, vil02 commented on src/main/java/com/thealgorithms/misc/MedianOfRunningArray.java
>      }
This is ugly. I think that it is fair to say that generics in Java are annoying. What do you think about defining the `MedianOfRunningArray` as abstract class (with `computeAverage` as an abstract method) and then have classes like `MedianOfRunningArrayInteger`, `MedianOfRunningArrayDouble` extending it?

In more details (I made some slight changes, please consider them):

```java
public abstract class MedianOfRunningArray<T extends Number & Comparable<T>> {

    private PriorityQueue<T> maxHeap = new PriorityQueue<>(Collections.reverseOrder());
    private PriorityQueue<T> minHeap = new PriorityQueue<>();

    /*
      Inserting lower half of array to max Heap
      and upper half to min heap
     */
    public void insert(final T e) {
        if (!minHeap.isEmpty() && e.compareTo(minHeap.peek()) < 0) {
            maxHeap.offer(e);
            if (maxHeap.size() > minHeap.size() + 1) {
                minHeap.offer(maxHeap.poll());
            }
        } else {
            minHeap.offer(e);
            if (minHeap.size() > maxHeap.size() + 1) {
                maxHeap.offer(minHeap.poll());
            }
        }
    }

    /*
      Returns median at any given point
     */
    public T median() {
        if (maxHeap.isEmpty() && minHeap.isEmpty()) {
            throw new IllegalArgumentException("Enter at least 1 element, Median of empty list is not defined!");
        } else if (maxHeap.size() == minHeap.size()) {
            T maxHeapTop = maxHeap.peek();
            T minHeapTop = minHeap.peek();
            return calculateAverage(maxHeapTop, minHeapTop);
        }
        return maxHeap.size() > minHeap.size() ? maxHeap.peek() : minHeap.peek();
    }

    public abstract T calculateAverage(T a, T b);
}
```

and

```java
final public class MedianOfRunningArrayDouble extends MedianOfRunningArray<Double> {
    @Override
    public Double calculateAverage(final Double a, final Double b) {
        return (a + b) / 2.0d;
    }
}
```

```java
final public class MedianOfRunningArrayInteger extends MedianOfRunningArray<Integer> {
    @Override
    public Integer calculateAverage(final Integer a, final Integer b) {
        return (a + b) / 2;
    }
}
```

Having `calculateAverage` as public will help with testing.

The advantage of this approach is that when someone wants to have a different rounding for integers it is enough to have `MedianOfRunningArrayIntegerCrazyRounding`.

2023-09-21 20:29 UTC, vil02 commented on src/test/java/com/thealgorithms/misc/MedianOfRunningArrayTest.java
Please clean-up the imports and the comment/documentation. I forgot to write that in the previous PR. Sorry.

2023-09-22 04:48 UTC, govardhanshah456 commented
@vil02 Hey ,as suggested I have made class abstract and did the required changes, have a look.

2023-09-22 14:09 UTC, vil02 requested changes
It goes in a very good direction!

2023-09-22 14:09 UTC, vil02 commented on src/main/java/com/thealgorithms/misc/MedianOfRunningArrayInteger.java
> +final public class MedianOfRunningArrayInteger extends MedianOfRunningArray<Integer> {
```suggestion
public final class MedianOfRunningArrayInteger extends MedianOfRunningArray<Integer> {
```

2023-09-22 14:09 UTC, vil02 commented on src/main/java/com/thealgorithms/misc/MedianOfRunningArrayLong.java
> +final public class MedianOfRunningArrayLong extends MedianOfRunningArray<Long> {
```suggestion
public final class MedianOfRunningArrayLong extends MedianOfRunningArray<Long> {
```

2023-09-22 14:09 UTC, vil02 commented on src/test/java/com/thealgorithms/misc/MedianOfRunningArrayTest.java
`import static org.junit.jupiter.api.Assertions.assertFalse;` and `import org.apache.commons.lang3.tuple.Pair;` are not needed.

The comments
```
/**
 * Test case for Two sum Problem.
 * @author Bama Charan Chhandogi (https://github.com/BamaCharanChhandogi)
 */
```
seems to be wrong.

2023-09-22 15:39 UTC, govardhanshah456 commented
@vil02 Hey, modified that comments and removed that impot and committed suggested changes, regarding double  and float i did not know that there exist some way to check precision using assertEqual itself, so was formatting at output side.

2023-09-22 16:00 UTC, vil02 submitted a review, later dismissed
Looks good. Thanks!

@siriak could you please have a look? There were _lots_ of new files introduced and I would like to double check if the current structure is correct.

2023-09-22 16:02 UTC, vil02 commented on src/main/java/com/thealgorithms/misc/MedianOfRunningArrayFloat.java
> +public final class MedianOfRunningArrayFloat extends MedianOfRunningArray<Float> {
```suggestion

public final class MedianOfRunningArrayFloat extends MedianOfRunningArray<Float> {
```

2023-09-22 16:03 UTC, vil02 approved these changes

2023-09-22 16:09 UTC, govardhanshah456 commented
Yeah, thanks.

2023-09-24 05:50 UTC, siriak approved these changes
Looks good, thanks!

2023-09-24 05:50 UTC, merged

2023-09-24 07:55 UTC, vil02 commented
@govardhanshah456 this was a good piece of Java programing. Thanks!