improved space complexity in SumOfDigit
TheAlgorithms/Java pull request #4393
Opened 2023-09-21 15:31 UTC by sam1231ui

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

hey, i have made SumOfDigit more efficient in space as now no need to make array you can review it

2023-09-21 20:39 UTC, vil02 requested changes
What is the difference between your suggestions and the method `sumOfDigits` defined earlier in this class?

Please remove the _commented out code_ and make sure that the _CI_ passes.

2023-09-21 20:40 UTC, Manan-09 commented on src/main/java/com/thealgorithms/maths/SumOfDigits.java
>          number = number < 0 ? -number : number;
We can just simply do 
`number = Math.abs(number)`
It will be more readable

2023-09-21 20:40 UTC, Manan-09 commented on src/main/java/com/thealgorithms/maths/SumOfDigits.java
>          for (int i = 0; i < digits.length; ++i) {
Instead of commenting previous code you can remove it

2023-09-22 05:20 UTC, closed without merging

2023-09-22 05:21 UTC, sam1231ui commented
everything was correct