#4387 Enhance Minimum sum partition problem implementation
TheAlgorithms/Java pull request #4394
Opened 2023-09-21 21:28 UTC by Manan-09

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
Resolves 

Testcase cover 100% code

<img width="911" alt="Screenshot 2023-09-22 at 2 50 15 AM" src="https://github.com/TheAlgorithms/Java/assets/76104205/a4245737-7788-4e56-8651-9f8b6b8eabad">

2023-09-22 14:43 UTC, vil02 requested changes
I would suggest to add the examples from the description to the test file.

Could you also update the description of the problem? At the moment is not very instructive.

Does it work for input array having negative numbers? This would need some explanation.

2023-09-22 14:43 UTC, vil02 commented on src/main/java/com/thealgorithms/dynamicprogramming/MinimumSumPartition.java
>  public class MinimumSumPartition {
```suggestion
public final class MinimumSumPartition {
```

It is a _utility class_, so there are no reasons to _extend_ it.

2023-09-22 14:43 UTC, vil02 commented on src/test/java/com/thealgorithms/dynamicprogramming/MinimumSumPartitionTest.java
> +
```suggestion
```

2023-09-22 14:43 UTC, vil02 commented on src/main/java/com/thealgorithms/dynamicprogramming/MinimumSumPartition.java
```suggestion
```

2023-09-22 20:15 UTC, Manan-09 commented
@vil02  This implementation is for non-negative numbers only.

2023-09-22 20:45 UTC, vil02 requested changes

2023-09-22 20:45 UTC, vil02 commented on src/main/java/com/thealgorithms/dynamicprogramming/MinimumSumPartition.java
> +Given an array of non-negative integers , partition the array in two subset that
If it is only for non-negative numbers, please check the input array and throw `IllegalArgumentException` when necessary, cf. https://github.com/TheAlgorithms/Java/pull/4368#issuecomment-1719945280

2023-09-22 20:45 UTC, vil02 commented on src/test/java/com/thealgorithms/dynamicprogramming/MinimumSumPartitionTest.java
> +import static org.junit.jupiter.api.Assertions.*;
```suggestion
import static org.junit.jupiter.api.Assertions.assertEquals;
```

2023-09-23 08:10 UTC, vil02 requested changes

2023-09-23 08:10 UTC, vil02 commented on src/test/java/com/thealgorithms/dynamicprogramming/MinimumSumPartitionTest.java
> +        });
```suggestion
        assertThrows(IllegalArgumentException.class, () -> { MinimumSumPartition.minimumSumPartition(array); });
```

2023-09-23 08:25 UTC, vil02 approved these changes

2023-09-23 08:26 UTC, merged