Single bit operators
TheAlgorithms/Java pull request #4415
Opened 2023-09-27 08:18 UTC by lukasb1b

#4350 as its not done yet

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-09-27 09:38 UTC, vil02 requested changes
I would suggest to rename this class to `SingleBitOperations`.

2023-09-27 09:38 UTC, vil02 commented on src/main/java/com/thealgorithms/bitmanipulation/SingleBitOperators.java
> +public class SingleBitOperators {
Let's make this class a _proper utility class_.

```suggestion
public final class SingleBitOperators {
    private SingleBitOperators() {
    }
```

2023-09-27 09:38 UTC, vil02 commented on src/main/java/com/thealgorithms/bitmanipulation/SingleBitOperators.java
> +    public static int flipBit(int num, int bit) {
```suggestion
    public static int flipBit(final int num, final int bit) {

```

2023-09-27 09:38 UTC, vil02 commented on src/main/java/com/thealgorithms/bitmanipulation/SingleBitOperators.java
> +    public static int setBit(int num, int bit) {
```suggestion
    public static int setBit(final int num, final int bit) {

```

2023-09-27 09:38 UTC, vil02 commented on src/main/java/com/thealgorithms/bitmanipulation/SingleBitOperators.java
> +    public static int clearBit(int num, int bit) {
```suggestion
    public static int clearBit(final int num, final int bit) {

```

2023-09-27 09:38 UTC, vil02 commented on src/main/java/com/thealgorithms/bitmanipulation/SingleBitOperators.java
> +    public static int getBit(int num, int bit) {
```suggestion
    public static int getBit(final int num, final int bit) {

```

2023-09-27 09:38 UTC, vil02 commented on src/test/java/com/thealgorithms/bitmanipulation/SingleBitOperatorTest.java
> +import static org.junit.jupiter.api.Assertions.*;
```suggestion
import static org.junit.jupiter.api.Assertions.assertEquals;

```

2023-09-28 16:42 UTC, vil02 requested changes
Why do you use the name `SingleBitOperator` and not `SingleBitOperations`?

I think the second name makes more sense in this context:
- this class defines _single bit operations_,
- it is not a _single bit operator_.

Please rebase (cf. #4422).

2023-09-28 16:42 UTC, vil02 commented on src/main/java/com/thealgorithms/bitmanipulation/SingleBitOperator.java
> +public final class SingleBitOperator {
As suggested [earlier](https://github.com/TheAlgorithms/Java/pull/4415#discussion_r1338339851):
```suggestion
public final class SingleBitOperator {
    private SingleBitOperator() {
    }
```

2023-09-29 06:28 UTC, lukasb1b reviewed
Why does the programm need this?

2023-09-29 07:11 UTC, vil02 commented
> Why does the programm need this private constructor?

Your class has only `static` methods. Therefore it does not really make sense to have objects of this class. Marking the default constructor as `private` (and not having other ones) makes it impossible to create objects of that class. Without this, one could still write something like `var obj = SingleBitOperator();`, but as said earlier, it does not really make sense.

Also JaCoCo will show now _100%_ coverage for your file.

2023-09-29 07:16 UTC, lukasb1b commented
Ok that does make sense

2023-09-29 19:28 UTC, vil02 commented
@lukasb1b please have a look at [this comment](https://github.com/TheAlgorithms/Java/pull/4415#pullrequestreview-1649293416) about renaming.

2023-09-30 08:04 UTC, lukasb1b commented
@vil02 changed the naming

2023-09-30 08:04 UTC, vil02 approved these changes

2023-09-30 08:06 UTC, merged