TowerOfHanoi-recursion
TheAlgorithms/Java pull request #4463
Opened 2023-09-30 21:37 UTC by sreshtech

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-09-30 23:28 UTC, vil02 requested changes
Always please make sure that the CI passes.

2023-09-30 23:28 UTC, vil02 commented on src/main/java/com/thealgorithms/backtracking/TowerOfHanoi.java
> +    }
Please remove the `main` method and instead add some proper tests. Good examples to look at:
- [`Factorial`](https://github.com/TheAlgorithms/Java/blob/566c27a996f48a94916170c159ae735546b39c42/src/main/java/com/thealgorithms/maths/Factorial.java) and [`FactorialTest`](https://github.com/TheAlgorithms/Java/blob/566c27a996f48a94916170c159ae735546b39c42/src/test/java/com/thealgorithms/maths/FactorialTest.java),
- [`FindMax`](https://github.com/TheAlgorithms/Java/blob/566c27a996f48a94916170c159ae735546b39c42/src/main/java/com/thealgorithms/maths/FindMax.java) and [`FindMaxTest`](https://github.com/TheAlgorithms/Java/blob/566c27a996f48a94916170c159ae735546b39c42/src/test/java/com/thealgorithms/maths/FindMaxTest.java).


```suggestion
```

2023-09-30 23:28 UTC, vil02 commented on src/main/java/com/thealgorithms/backtracking/TowerOfHanoi.java
> +public class TowerOfHanoi {
Let's make it a _proper utility class_.

```suggestion
public final class TowerOfHanoi {
    private TowerOfHanoi() {
    }
```

2023-10-01 00:13 UTC, sreshtech commented
> Always please make sure that the CI passes and _check_ all of the _boxes_ in the PR (i.e. change `[ ]` to `[x]`).

DONE
Removed the main method and  added some proper tests.
PLEASE  ask to resolve if more issues. thank you!

2023-10-01 20:54 UTC, BamaCharanChhandogi commented
@vil02 The Tower of Hanoi is already available.

2023-10-02 04:03 UTC, BamaCharanChhandogi commented
I am closing this issue.

2023-10-02 04:03 UTC, closed without merging