Greedy Algorithm Implementations and Explanations #4493
TheAlgorithms/Java pull request #4504
Opened 2023-10-01 14:52 UTC by Vineetttt

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-10-01 19:58 UTC, siriak requested changes
The code looks good, could you please remove `main`, logging to console, and add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

2023-10-01 20:06 UTC, Vineetttt commented
> The code looks good, could you please remove `main`, logging to console, and add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

@siriak Yes I'll do the changes but can you elaborate a bit, what exactly needs to be done

2023-10-01 21:51 UTC, Vineetttt commented
@siriak I've made the necessary changes you can check.

2023-10-01 22:13 UTC, Vineetttt commented
@siriak I've made the necessary changes you can check and merge accordingly.

2023-10-02 06:53 UTC, Vineetttt reviewed
I've made the necessary changes you can check and merge accordingly.

2023-10-02 11:08 UTC, siriak requested changes
Please fix PR checks

2023-10-02 11:08 UTC, siriak commented on src/main/java/com/thealgorithms/greedyalgorithms/ActivitySelection.java
> +    public static void printActivities(ArrayList<Integer> ans) {
No need to print anything, presentation should be separate from the algorithm

2023-10-02 11:08 UTC, siriak commented on src/test/java/com/thealgorithms/greedyalgorithms/CoinChangeTest.java
> +        ArrayList<Integer> expected = new ArrayList<>(Arrays.asList(500, 50, 20, 20, 1));
Please add tests where not all coins are used.

2023-10-02 11:08 UTC, siriak commented on src/test/java/com/thealgorithms/greedyalgorithms/DijkstrasAlgorithmTest.java
> +        int[][] graph = {{0, 2, 4, 0, 0, 0}, {0, 0, 1, 7, 0, 0}, {0, 0, 0, 0, 3, 0}, {0, 0, 0, 0, 0, 1}, {0, 0, 0, 2, 0, 5}, {0, 0, 0, 0, 0, 0}};
Dijkstras algorithm is already implemented

2023-10-02 11:28 UTC, Vineetttt reviewed
Appropriate changes are made, can you check.

2023-10-02 19:58 UTC, siriak commented on src/test/java/com/thealgorithms/greedyalgorithms/CoinChangeTest.java
> +        ArrayList<Integer> expected = new ArrayList<>(Arrays.asList(500, 50, 20, 20, 1));
This is not addressed

2023-10-02 20:00 UTC, siriak commented
Please fix the linter job which is failing and add more tests for coin change

2023-10-03 08:22 UTC, Vineetttt commented
@siriak Necessary changes are made, you can check .

2023-10-03 14:17 UTC, siriak requested changes

2023-10-03 14:17 UTC, siriak commented on src/test/java/com/thealgorithms/greedyalgorithms/CoinChangeTest.java
> +        ArrayList<Integer> expected = new ArrayList<>(Arrays.asList(500, 50, 20, 20, 1));
This is not addressed

2023-10-03 17:27 UTC, siriak approved these changes

2023-10-03 17:30 UTC, merged