Buyandsellstocks
TheAlgorithms/Java pull request #4615
Opened 2023-10-04 01:56 UTC by BharathSubu

Adding Buy and Sell Stocks
Fixes #4569

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-10-04 19:23 UTC, Manan-09 commented on src/main/java/com/thealgorithms/dynamicprogramming/BuyAndSellStock.java
> + * Find and return the maximum profit you can achieve.
@BharathSubu  can we buy and sell stock as many times as we want?
If that is the case , we can find maximum profit in O(n) TC and O(1) SC , using greedy approch

2023-10-21 15:22 UTC, vil02 requested changes
@BharathSubu please add tests for the provided implementation.

Some examples to look at:
- [`FactorialTest.java`](https://github.com/TheAlgorithms/Java/blob/master/src/test/java/com/thealgorithms/maths/FactorialTest.java),
- [`SecondMinMaxTest.java`](https://github.com/TheAlgorithms/Java/blob/master/src/test/java/com/thealgorithms/maths/SecondMinMaxTest.java).

2023-10-21 15:22 UTC, vil02 commented on src/main/java/com/thealgorithms/dynamicprogramming/BuyAndSellStock.java
> +    }
This is not needed.
```suggestion
```

2023-10-21 15:22 UTC, vil02 commented on src/main/java/com/thealgorithms/dynamicprogramming/BuyAndSellStock.java
> +import java.util.Scanner;
```suggestion
```

2023-10-21 15:22 UTC, vil02 commented on src/main/java/com/thealgorithms/dynamicprogramming/BuyAndSellStock.java
> +// https://en.wikipedia.org/wiki/Dynamic_programming
Please add an exact link with the description of the problem and its solution.

2024-01-31 00:19 UTC, closed without merging