implemented ExchangeSort under sort alogorithms
TheAlgorithms/Java pull request #4627
Opened 2023-10-04 07:29 UTC by absharul

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-10-04 07:30 UTC, absharul commented
Implemented ExchangeSort algorithm

2023-10-04 07:48 UTC, absharul commented on src/main/java/com/thealgorithms/sorts/ExchangeSort.java
> +package com.thealgorithms.sorts;
```suggestion
package com.thealgorithms.sorts;
```

2023-10-04 14:57 UTC, BamaCharanChhandogi commented
solve clang issue. and then add the test cases file.

2023-10-04 17:34 UTC, absharul commented
> solve clang issue. and then add the test cases file.

Hey BamaCharanChhandogi I'm pleased to inform you that I have successfully resolved the Clang issue.

2023-10-06 11:46 UTC, absharul commented
would you please check this PR??

2023-10-24 16:56 UTC, BamaCharanChhandogi requested changes
Remove the main method, then add a test case file.

2024-01-28 00:21 UTC, closed without merging