Create ArrayRightRotation.java
TheAlgorithms/Java pull request #4682
Opened 2023-10-05 22:07 UTC by ppiippoo

Resolving issue #4638
( [FEATURE REQUEST] Array Right Rotation #4638 )

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-10-22 11:16 UTC, vil02 commented
Closes #4638.

2023-10-22 11:19 UTC, vil02 requested changes
Most important thins: please add tests. Some examples to look at:
- [`FactorialTest.java`](https://github.com/TheAlgorithms/Java/blob/master/src/test/java/com/thealgorithms/maths/FactorialTest.java),
- [`SecondMinMaxTest.java`](https://github.com/TheAlgorithms/Java/blob/master/src/test/java/com/thealgorithms/maths/SecondMinMaxTest.java).

2023-10-22 11:19 UTC, vil02 commented on src/main/java/com/thealgorithms/others/ArrayRightRotation.java
> +public class ArrayLeftRotation {
It can be a _proper utility class_.
```suggestion
public final class ArrayLeftRotation {
    private ArrayLeftRotation() {
    }
```

2023-10-22 11:19 UTC, vil02 commented on src/main/java/com/thealgorithms/others/ArrayRightRotation.java
> +     */
```suggestion
    /*
     * @brief rotates the input array by given number of steps.
     * @param arr : int[] given array
     * @param n : int given integer
     * @return : the result of right rotation of given array arr and integer n
     */
```

2023-10-26 19:27 UTC, vil02 commented
@ppiippoo what is the progresses?

2024-01-12 03:31 UTC, BamaCharanChhandogi commented
The code is wrong. you have not corrected it yet! so, I am closing this PR.

2024-01-12 03:31 UTC, closed without merging