Min value Test
TheAlgorithms/Java pull request #4713
Opened 2023-10-07 17:10 UTC by lukasb1b

Adding Test to MinValue

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.

2023-10-08 13:20 UTC, vil02 commented
@lukasb1b where are the tests?

2023-10-08 18:11 UTC, lukasb1b commented
@vil02 sry I forgot to mearch a branch

2023-10-08 18:41 UTC, vil02 requested changes
I would use the opportunity and update the doc-string.

2023-10-08 18:41 UTC, vil02 commented on src/test/java/com/thealgorithms/maths/MinValueTest.java
> +    public void flipBitTest() {
```suggestion
    public void minTest() {
```

2023-10-08 18:41 UTC, vil02 commented on src/test/java/com/thealgorithms/maths/MinValueTest.java
> +    }
```suggestion
        assertEquals(5, MinValue.min(5, 5));
    }
```

2023-10-08 18:41 UTC, vil02 commented on src/main/java/com/thealgorithms/maths/MinValue.java
>  public class MinValue {
```suggestion
public final class MinValue {
    private MinValue() {
    }
```

2023-10-08 18:49 UTC, lukasb1b commented
Sure upadte it. I think you should be able to change the file.

2023-10-09 15:13 UTC, vil02 approved these changes

2023-10-09 15:17 UTC, merged