Added test cases for RodCuttingTest.java
TheAlgorithms/Java pull request #4744
Opened 2023-10-09 11:08 UTC by sunilnitdgp

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [ ] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2023-10-09 14:32 UTC, sunilnitdgp commented
I request the maintainer(s) to merge my request using "hacktoberfest-accepted" label.

2023-10-09 18:54 UTC, vil02 requested changes
Please:
- remove the `main` method,
- mark `RodCutting` as `final`,
- add a `private` default constructor of `RodCutting`.

2023-10-11 12:31 UTC, siriak commented
Linter is still failing

2023-10-11 17:08 UTC, sunilnitdgp commented
@siriak Fixed the linter issue.

2023-10-12 16:58 UTC, sunilnitdgp commented
@vil02 / @siriak Please review this and merge if everything looks good.

2023-10-12 17:33 UTC, vil02 commented on src/test/java/com/thealgorithms/dynamicprogramming/RodCuttingTest.java
> +    }
@sunilnitdgp this is still pending.

2023-10-12 19:29 UTC, siriak commented on src/test/java/com/thealgorithms/dynamicprogramming/RodCuttingTest.java
> +    }
Please provide a source of the test data or the method used to create it

2024-01-09 00:20 UTC, closed without merging