Create DuplicateStack.java
TheAlgorithms/Java pull request #4772
Opened 2023-10-11 16:52 UTC by Khandelwal05

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2023-10-12 03:47 UTC, Khandelwal05 commented
@yanglbme @debasishbsws @vil02 @BamaCharanChhandogi please review my PR under hacktoberfest and hacktoberfest-accepted label.

2023-10-12 03:47 UTC, Khandelwal05 commented
@yanglbme @debasishbsws @vil02 @BamaCharanChhandogi please review my PR under hacktoberfest and hacktoberfest-accepted label.

2023-10-13 04:40 UTC, susanhsrestha requested changes
You can optimize the code following the provided suggestions.

2023-10-13 04:40 UTC, susanhsrestha commented on src/main/java/com/thealgorithms/stacks/DuplicateStack.java
> +        dupSt2 = new int[max_a];
This duplicate array can have the length of _max_ instead of max_a
`dupSt2 = new int[max];`

2023-10-13 04:40 UTC, susanhsrestha commented on src/main/java/com/thealgorithms/stacks/DuplicateStack.java
> +        int[] dupSt = new int[max_a];
This duplicate array can have the length of _max_ instead of max_a.
Or you don't even need this array if you optimize your code.

2023-10-13 04:40 UTC, susanhsrestha commented on src/main/java/com/thealgorithms/stacks/DuplicateStack.java
> +        for (int j = top; j >= 0; j--) {
You can eliminate this iteration if you optimize the code and don't use another stack array.

2023-10-13 04:40 UTC, susanhsrestha commented on src/main/java/com/thealgorithms/stacks/DuplicateStack.java
> +        for (int j = topx; j >= 0; j--) {
You can use this single iteration to duplicate the stack.
`for (int j = top; j >= 0; j--) {`
`            top2++;`
`            dupSt2[j] = St[j];`
`        }`

2023-10-14 00:38 UTC, Khandelwal05 commented
@yanglbme @debasishbsws @vil02 @BamaCharanChhandogi please review my PR under hacktoberfest and hacktoberfest-accepted label.

2023-10-14 00:44 UTC, Khandelwal05 commented
@yanglbme @debasishbsws @vil02 @BamaCharanChhandogi please review my PR under hacktoberfest and hacktoberfest-accepted label.

2023-10-14 18:13 UTC, susanhsrestha requested changes
Store the duplicate in an array

2023-10-14 18:13 UTC, susanhsrestha commented on src/main/java/com/thealgorithms/stacks/DuplicateStack.java
> +    public static void duplicate(int[] stack) {
Store the duplicate stack in an array and maybe also return it.

2023-10-15 01:42 UTC, Khandelwal05 commented
@yanglbme @debasishbsws @vil02 @BamaCharanChhandogi please review my PR under hacktoberfest and hacktoberfest-accepted label.

2023-10-15 03:37 UTC, susanhsrestha approved these changes
LGTM!

2023-10-15 13:13 UTC, susanhsrestha approved these changes
Looks good to me, LGTM!

2024-01-07 00:22 UTC, closed without merging