Implementing Stack Using Queues
TheAlgorithms/Java pull request #4962
Opened 2023-11-15 07:20 UTC by sricharan200

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

Note: I have raised a pull request. This is part of my coursework. Kindly, look into it. Thank you.

2023-11-15 08:05 UTC, siriak requested changes
Could you please replace main with some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

2023-11-15 22:22 UTC, sricharan200 commented
> Could you please replace main with some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

Hi, do you want me to push the code to the test folder instead of the main folder?

Correct me if I am wrong

2023-11-15 22:31 UTC, sricharan200 commented
> Could you please replace main with some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

I have made the required changes. Kindly, look into it. Thank you.

2023-11-16 21:50 UTC, siriak requested changes
Please review your submission. The implementation must be in StackUsingQueues.java and tests must be in StackUsingQueuesTests.java in tests folder. Also see PR checks that fail for details

2023-11-16 23:48 UTC, sricharan200 commented
> Please review your submission. The implementation must be in StackUsingQueues.java and tests must be in StackUsingQueuesTests.java in tests folder. Also see PR checks that fail for details

I have made necessary changes. Kindly, look into it. Thank you

2023-11-17 08:47 UTC, siriak requested changes
Please add a test with more items in stack (at least 5) and fix PR checks, everything else looks good
![image](https://github.com/TheAlgorithms/Java/assets/29201949/4b9d909e-5a0b-4c35-8b92-481285518401)

2023-11-17 08:47 UTC, siriak commented on src/main/java/com/thealgorithms/stacks/StackUsingQueues.java
> +    public static void main(String[] args) {
Please remove `main`, we don't need it. Tests already test the implementation

2023-11-17 14:28 UTC, sricharan200 commented
Hey, I have made the changes. Please look into it. Thank you.

2023-11-17 17:12 UTC, BamaCharanChhandogi requested changes
There was a small 'clang' issue. Please solve it.
Your test cases are failing. Try to resolve the issue in your test cases

2023-12-26 00:19 UTC, closed without merging