Added Playfair Cipher
TheAlgorithms/Java pull request #4988
Opened 2024-01-02 16:52 UTC by Govind516

- [ x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ x] This pull request is all my own work -- I have not plagiarized it.
- [ x] All filenames are in PascalCase.
- [ x] All functions and variable names follow Java naming conventions.

2024-01-02 17:51 UTC, siriak requested changes
The code looks good, could you please add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

2024-01-02 18:04 UTC, Govind516 commented
okay. I will add JUnit Tests.

2024-01-02 18:45 UTC, Govind516 commented
could you please check now as changes meets the requirements.

2024-01-02 20:36 UTC, siriak requested changes
Please fix the failing linter check
![image](https://github.com/TheAlgorithms/Java/assets/29201949/664d684c-f187-4065-974a-17145b4ee88d)

2024-01-02 20:36 UTC, siriak commented on src/main/java/com/thealgorithms/ciphers/PlayfairCipher.java
> +    public static void main(String[] args) {
Please remove `main`, it's not needed

2024-01-03 04:38 UTC, Govind516 commented
Removed the _main_ function and also solved Clang format. Please check now.

2024-01-03 13:14 UTC, siriak approved these changes
Looks good, thanks!

2024-01-03 13:14 UTC, merged