chore: simplified minimizing lateness
TheAlgorithms/Java pull request #4999
Opened 2024-01-07 04:28 UTC by inishantjain

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2024-01-07 11:17 UTC, siriak requested changes
The code looks good, could you please add some JUnit tests? (see https://github.com/TheAlgorithms/Java/tree/master/src/test/java/com/thealgorithms)

2024-01-07 11:23 UTC, inishantjain commented
I'll do it. ☑️

2024-01-07 22:53 UTC, siriak requested changes

2024-01-07 22:53 UTC, siriak commented on src/main/java/com/thealgorithms/greedyalgorithms/MinimizingLateness.java
> +    public static void main(String[] args) {
Please remove `main`, it's not needed because JUnit tests already test everything

2024-01-07 22:53 UTC, siriak commented on src/test/java/com/thealgorithms/greedyalgorithms/MinimizingLatenessTest.java
> +public class MinimizingLatenessTest extends MinimizingLateness {
Please don't extend it, but call its methods without inheritance

2024-01-08 13:34 UTC, siriak approved these changes
Looks good, thanks!

2024-01-08 13:34 UTC, merged