Feature/4638 array right rotation
TheAlgorithms/Java pull request #5014
Opened 2024-01-12 18:06 UTC by SarthakChaudhary46

Done with the changes✅

Done with the requested changes.✅

2024-01-12 18:25 UTC, BamaCharanChhandogi requested changes
please change these.

2024-01-12 18:26 UTC, BamaCharanChhandogi commented on src/test/java/com/thealgorithms/others/ArrayRightRotation.java
> +class ArrayRightRotation {
add `public` before class

2024-01-12 18:26 UTC, BamaCharanChhandogi commented on src/test/java/com/thealgorithms/others/ArrayRightRotation.java
> +    static int[] rotateRight(int[] arr, int k) {
same add `public` keyword

2024-01-13 06:59 UTC, SarthakChaudhary46 commented
> please change these.

- done with all the changes✅

2024-01-13 07:05 UTC, BamaCharanChhandogi commented on src/test/java/com/thealgorithms/others/ArrayRightRotationTest.java
> +    @Test
add different test cases. You can reference this code.
[https://github.com/TheAlgorithms/Java/blob/master/src/test/java/com/thealgorithms/others/ArrayLeftRotationTest.java](url)

2024-01-13 07:34 UTC, SarthakChaudhary46 commented
Please have a look now!

2024-01-13 08:28 UTC, BamaCharanChhandogi commented
thanks, LGTM.

2024-01-13 08:28 UTC, BamaCharanChhandogi approved these changes

2024-01-13 08:29 UTC, merged