style: enable StaticVariableName in checkstyle
TheAlgorithms/Java pull request #5173
Opened 2024-05-24 12:13 UTC by vaibhav9t1

Related to #5119

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2024-05-24 22:14 UTC, vil02 requested changes

2024-05-24 22:14 UTC, vil02 commented on src/main/java/com/thealgorithms/ciphers/DES.java
It seems that all of the `static` variables in `DES`, could be `final`. Could you please mark them as `private static final` and do the suitable renaming?

2024-05-25 06:58 UTC, vaibhav9t1 commented on src/main/java/com/thealgorithms/ciphers/DES.java
Done

2024-05-25 14:07 UTC, vil02 approved these changes

2024-05-25 14:09 UTC, merged