refactor: redesign `LetterCombinationsOfPhoneNumber`
TheAlgorithms/Java pull request #5221
Opened 2024-06-12 11:29 UTC by samuelfac

Related to #5164

- [X] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [X] This pull request is all my own work -- I have not plagiarized it.
- [X] All filenames are in PascalCase.
- [X] All functions and variable names follow Java naming conventions.
- [X] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [X] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2024-06-12 15:01 UTC, vil02 requested changes

2024-06-12 15:01 UTC, vil02 commented on src/test/java/com/thealgorithms/strings/LetterCombinationsOfPhoneNumberTest.java
>      }
```suggestion
        private static Stream<Arguments> provideTestCases() {
        return Stream.of(Arguments.of(null, List.of("")), Arguments.of(new int[] {}, List.of("")), Arguments.of(new int[] {2}, Arrays.asList("a", "b", "c")), Arguments.of(new int[] {2, 3}, Arrays.asList("ad", "ae", "af", "bd", "be", "bf", "cd", "ce", "cf")),
            Arguments.of(new int[] {2, 3, 4}, Arrays.asList("adg", "adh", "adi", "aeg", "aeh", "aei", "afg", "afh", "afi", "bdg", "bdh", "bdi", "beg", "beh", "bei", "bfg", "bfh", "bfi", "cdg", "cdh", "cdi", "ceg", "ceh", "cei", "cfg", "cfh", "cfi")));
    }
```

I agree that the current formatting settings are a bit strange, but let's not fight against it with adding `//`.

What do you think about adding a test case, where the number are not sorted (e.g. `{8, 4}`) or contain duplicates (e.g. `{5, 5}`).

2024-06-12 15:31 UTC, vil02 commented on src/test/java/com/thealgorithms/strings/LetterCombinationsOfPhoneNumberTest.java
> +            Arguments.of(new int[] {2, 3, 4}, Arrays.asList("adg", "adh", "adi", "aeg", "aeh", "aei", "afg", "afh", "afi", "bdg", "bdh", "bdi", "beg", "beh", "bei", "bfg", "bfh", "bfi", "cdg", "cdh",
Please add a test case with `{8, 4}` (_not sorted input_) and `{3, 3}` (_duplicates_).

2024-06-12 18:15 UTC, vil02 submitted a review, later dismissed
I allowed myself to push one commit into your branch: 910c814d2a7152abcd5a4a03f161463f45d65402 I hope you don't mind.

The code looks good. I am just wondering if it makes sense to change the `KEYPAD` to a simple array. Let me know about your opinion.

2024-06-12 18:15 UTC, vil02 commented on src/main/java/com/thealgorithms/strings/LetterCombinationsOfPhoneNumber.java
> +    private static final Map<Integer, String> KEYPAD = Map.of(0, " ", 1, "", 2, "abc", 3, "def", 4, "ghi", 5, "jkl", 6, "mno", 7, "pqrs", 8, "tuv", 9, "wxyz");
This could actually be simple array. Please let me know about your opinion.

2024-06-13 08:48 UTC, vil02 requested changes

2024-06-13 08:48 UTC, vil02 commented on src/main/java/com/thealgorithms/strings/LetterCombinationsOfPhoneNumber.java
> +    private static final List<String> KEYPAD = List.of(" ", "", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz");
Why not simply

```suggestion
    private static final String[] KEYPAD = new String[] {" ", "", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz"};
```

2024-06-13 08:48 UTC, vil02 commented on src/main/java/com/thealgorithms/strings/LetterCombinationsOfPhoneNumber.java
> +        for (char letter : letters.toCharArray()) {
```suggestion
        for (char letter : KEYPAD[number].toCharArray()) {
```

2024-06-13 08:48 UTC, vil02 commented on src/main/java/com/thealgorithms/strings/LetterCombinationsOfPhoneNumber.java
> +        final String letters = KEYPAD.get(number); // Get corresponding letters for the current number
```suggestion
```

2024-06-13 09:28 UTC, vil02 commented on src/main/java/com/thealgorithms/strings/LetterCombinationsOfPhoneNumber.java
> +    private static final String[] KEYPAD = new String[] {" ", "", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz"};
```suggestion
    private static final String[] KEYPAD = new String[] {"", "", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz"};
```

I think this space was introduced by accident in 06d49ced305423dba456fcb710a74506b2169b57.

2024-06-13 11:51 UTC, vil02 commented on src/main/java/com/thealgorithms/strings/LetterCombinationsOfPhoneNumber.java
> +    private static final String[] KEYPAD = new String[] {" ", EMPTY + "", "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz"};
```suggestion
    private static final String[] KEYPAD = new String[] {" ", String.valueOf(EMPTY), "abc", "def", "ghi", "jkl", "mno", "pqrs", "tuv", "wxyz"};
```

2024-06-13 17:22 UTC, vil02 commented on src/test/java/com/thealgorithms/strings/LetterCombinationsOfPhoneNumberTest.java
> +        assertLinesMatch(expectedOutput, LetterCombinationsOfPhoneNumber.getCombinations(numbers));
@samuelfac could you please have a look?

2024-06-13 17:38 UTC, vil02 approved these changes

2024-06-13 17:40 UTC, merged

2024-10-03 02:26 UTC, Theghost256 approved these changes