Fix Swap Sort Implementation: Correct Logic and Improve Efficiency
TheAlgorithms/Java pull request #5248
Opened 2024-06-23 12:19 UTC by alxkm

There was an issue where this sorting implementation could enter an infinite loop, such as in the test shouldAcceptWhenArrayWithDuplicateValueIsPassed. 

The index variable was not being updated correctly.
The index may never reach len - 1 due to the flawed logic, leading to a potential infinite loop. 

This fix addresses the issue and adds the missing test for this sorting algorithm.

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [ ] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2024-06-23 16:25 UTC, vil02 requested changes

2024-06-23 16:25 UTC, vil02 commented on src/main/java/com/thealgorithms/sorts/SwapSort.java
I think this has become some bubble sort. In order to fix this issue, I would suggest something like this:
```java
public class SwapSort implements SortAlgorithm {

    @Override
    public <T extends Comparable<T>> T[] sort(T[] array) {
        int len = array.length;
        int index = 0;

        while (index < len - 1) {
            int amountSmallerElements = this.getSmallerElementCount(array, index);

            if (amountSmallerElements > 0) {
                SortUtils.swap(array, index, index + amountSmallerElements);
            } else {
                index++;
            }
        }

        return array;
    }

    private <T extends Comparable<T>> int getSmallerElementCount(T[] array, int index) {
        int counter = 0;
        for (int i = index + 1; i < array.length; i++) {
            if (SortUtils.less(array[i], array[index])) {
                counter++;
            }
        }

        return counter;
    }
}
```

2024-06-23 21:55 UTC, alxkm commented on src/main/java/com/thealgorithms/sorts/SwapSort.java
You are right. Thanks. Missed that such variant looks like bubble sort.

2024-06-24 06:45 UTC, vil02 approved these changes

2024-06-24 06:49 UTC, merged