Create StalinSort.java
TheAlgorithms/Java pull request #5720
Opened 2024-10-11 11:26 UTC by anant-jain01

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [ ] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2024-10-11 13:06 UTC, saahil-mahato commented on src/main/java/com/thealgorithms/sorts/StalinSort.java
> +    private <T> T[] trimArray(T[] array, int length) {
I think this is redundant. Is there a reason to use this?

2024-10-11 13:11 UTC, saahil-mahato commented on src/main/java/com/thealgorithms/sorts/StalinSort.java
> +    private <T> T[] trimArray(T[] array, int length) {
This just adds unnecessary overhead. We can remove this if we just use ArrayList.
```
List<T> result = new ArrayList<>();
        result.add(array[0]); 

        for (int i = 1; i < array.length; i++) {
            if (SortUtils.less(result.get(result.size() - 1), array[i])) {
                result.add(array[i]);
            }
        }
```

2024-10-11 13:12 UTC, saahil-mahato commented on src/main/java/com/thealgorithms/sorts/StalinSort.java
> +        if (array.length == 0) {
add `null` check here to prevent null pointer expection.

2024-10-11 13:13 UTC, saahil-mahato commented
Please add tests.

2024-10-12 07:12 UTC, siriak requested changes
Please add JUnit tests

2024-11-19 00:27 UTC, closed without merging