feat: add bresenham's line drawing algorithm
TheAlgorithms/Java pull request #5779
Opened 2024-10-13 14:21 UTC by saahil-mahato

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2024-10-14 21:50 UTC, alxkm requested changes

2024-10-14 21:50 UTC, alxkm commented on src/main/java/com/thealgorithms/geometry/BresenhamLine.java
> +    public List<Point> findLine(int x0, int y0, int x1, int y1) {
This method could be static

2024-10-14 21:50 UTC, alxkm commented on src/test/java/com/thealgorithms/geometry/BresenhamLineTest.java
> +class BresenhamLineTest {
Will be better to use Parametrized Tests for this class. Because all tests are the similar, only test data different

2024-10-14 21:50 UTC, alxkm commented on src/main/java/com/thealgorithms/geometry/BresenhamLine.java
> +            int e2 = err * 2;
Could be final

2024-10-15 00:19 UTC, saahil-mahato commented
@alxkm I have resolved the comments. Please review and let me know if anything is missing. Thanks

2024-10-15 09:10 UTC, alxkm approved these changes
Thank you for your contribution.

2024-10-15 09:13 UTC, merged