Implement a function to compute the nth Catalan number
TheAlgorithms/Java pull request #5846
Opened 2024-10-15 09:43 UTC by UTSAVS26

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2024-10-16 04:10 UTC, saahil-mahato requested changes

2024-10-16 04:10 UTC, saahil-mahato commented on src/test/java/com/thealgorithms/maths/CatalanNumbersTest.java
> +    void testCatalanNumbers() {
Better to convert this into a parameterized test,

2024-10-16 06:38 UTC, UTSAVS26 commented
@saahil-mahato changes made as per requested, thank you for your time.

2024-10-20 10:15 UTC, UTSAVS26 commented
@alxkm please review my PR.

2024-10-26 09:58 UTC, siriak approved these changes
Looks good, thanks!

2024-10-26 10:10 UTC, merged