Added Maximum Sliding Window algorithm using deque for efficient O(n) solution.
TheAlgorithms/Java pull request #5848
Opened 2024-10-15 10:16 UTC by pranayh24

- [ ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [ ] This pull request is all my own work -- I have not plagiarized it.
- [ ] All filenames are in PascalCase.
- [ ] All functions and variable names follow Java naming conventions.
- [ ] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [ ] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2024-10-15 11:12 UTC, pranayh24 commented
Pull Request Description
Title: Add Maximum Sliding Window Algorithm Implementation

Overview: This pull request adds an implementation of the Maximum Sliding Window algorithm using a deque (double-ended queue) for efficient O(n) time complexity. The algorithm allows you to find the maximum value in every sliding window of size k in an array of integers.

Key Features:

Efficient Implementation: Utilizes a deque to maintain the indices of useful elements in the current window, allowing for optimal performance.
Input and Output:
Input: An array of integers and a window size k.
Output: An array of the maximum values for each sliding window.
Space Complexity: O(k) for the deque, which holds at most k elements at any time.

Feedback: I welcome any feedback or suggestions for improvements on this implementation.

2024-10-16 02:18 UTC, saahil-mahato requested changes

2024-10-16 02:18 UTC, saahil-mahato commented on src/main/java/com/thealgorithms/others/MaximumSlidingWindow.java
> +    public static void main(String[] args) {
Please remove the `main` function and add tests.

2024-10-26 09:17 UTC, siriak approved these changes
Looks good, thanks!

2024-10-26 19:05 UTC, merged