Add LongestCommonPrefix.java
TheAlgorithms/Java pull request #5849
Opened 2024-10-15 11:11 UTC by TheDarkW3b

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2024-10-16 02:16 UTC, saahil-mahato requested changes

2024-10-16 02:16 UTC, saahil-mahato commented on src/main/java/com/thealgorithms/strings/LongestCommonPrefix.java
> +public final class LongestCommonPrefix {
Please add tests.

2024-10-16 02:16 UTC, saahil-mahato commented on src/main/java/com/thealgorithms/strings/LongestCommonPrefix.java
> +        if(strs == null || strs.length == 0) return "";
Please follow styling standard. `if` block should be inside `{}`.

2024-10-16 02:16 UTC, saahil-mahato commented on src/main/java/com/thealgorithms/strings/LongestCommonPrefix.java
> +        while(index < shortest.length() && index < longest.length() && shortest.charAt(index) == longest.charAt(index))
Please follow styling standard. `while` block should also be inside `{}`.

2024-10-16 16:42 UTC, TheDarkW3b commented
Let me know if any changed are required.. also please add the hacktoberfest label

2024-10-19 05:07 UTC, TheDarkW3b commented
Let me know if any changes are required.. also please add the hacktoberfest label

2024-10-26 09:50 UTC, siriak approved these changes
Looks good, thanks!

2024-10-26 19:01 UTC, merged