refactor: Enhance docs, add more tests in `SwapAdjacentBits`
TheAlgorithms/Java pull request #5861
Opened 2024-10-16 03:26 UTC by Hardvan

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2024-10-26 09:00 UTC, siriak requested changes

2024-10-26 09:00 UTC, siriak commented on src/main/java/com/thealgorithms/bitmanipulation/SwapAdjacentBits.java
>          evenBits >>= 1;
Please return comments

2024-10-29 04:36 UTC, Hardvan commented on src/main/java/com/thealgorithms/bitmanipulation/SwapAdjacentBits.java
>          evenBits >>= 1;
Done!

2024-10-29 17:51 UTC, siriak approved these changes

2024-10-29 18:12 UTC, merged