refactor: Enhance docs, add tests in `GenericHashMapUsingArray`
TheAlgorithms/Java pull request #5972
Opened 2024-10-24 05:53 UTC by Hardvan

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2024-10-26 11:31 UTC, siriak requested changes

2024-10-26 11:31 UTC, siriak commented on src/main/java/com/thealgorithms/datastructures/hashmap/hashing/GenericHashMapUsingArray.java
>          System.out.println("Rehashing!");
Please remove printing to console

2024-10-29 04:34 UTC, Hardvan commented on src/main/java/com/thealgorithms/datastructures/hashmap/hashing/GenericHashMapUsingArray.java
>          System.out.println("Rehashing!");
Done!

2024-10-29 17:51 UTC, siriak approved these changes

2024-10-29 18:51 UTC, merged