refactor: Enhance docs, add tests in `GenericHeap`
TheAlgorithms/Java pull request #5980
Opened 2024-10-24 06:33 UTC by Hardvan

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2024-10-26 11:36 UTC, siriak requested changes

2024-10-26 11:36 UTC, siriak commented on src/test/java/com/thealgorithms/datastructures/heaps/GenericHeapTest.java
> +        heap.display(); // Just checking no exceptions are thrown.
Please remove display

2024-10-29 04:32 UTC, Hardvan commented on src/test/java/com/thealgorithms/datastructures/heaps/GenericHeapTest.java
> +        heap.display(); // Just checking no exceptions are thrown.
Done!

2024-10-29 17:51 UTC, siriak approved these changes

2024-10-29 20:11 UTC, merged