Speed up DijkstraAlgorithm
TheAlgorithms/Java pull request #6088
Opened 2024-11-13 13:47 UTC by likespro

Speed up Dijkstra Algorithm by using another Dijkstra variant that is generally faster.

- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).
- [x] This pull request is all my own work -- I have not plagiarized it.
- [x] All filenames are in PascalCase.
- [x] All functions and variable names follow Java naming conventions.
- [x] All new algorithms have a URL in their comments that points to Wikipedia or other similar explanations.
- [x] All new code is formatted with `clang-format -i --style=file path/to/your/file.java`

2024-11-15 17:34 UTC, siriak requested changes
Could you add this as a separate optimized implementation? Both are good. The proposed one is faster, but the original one is simpler and easier to understand.

2024-11-18 19:07 UTC, siriak requested changes

2024-11-18 19:07 UTC, siriak commented on src/main/java/com/thealgorithms/datastructures/graphs/DijkstraOptimizedAlgorithm.java
> +    private void printDistances(int[] distances) {
Please remove printing

2024-11-18 19:31 UTC, likespro commented on src/main/java/com/thealgorithms/datastructures/graphs/DijkstraOptimizedAlgorithm.java
> +    private void printDistances(int[] distances) {
Removed

2024-11-19 07:08 UTC, siriak approved these changes
Looks good, thanks!

2024-11-19 07:09 UTC, merged